### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by allout58** [jshiell/checkstyle-idea#131]
Sounds very similar to some other reported issues ( #90 and #82), but thought I'd go ahead and put my stacktraces and info here.  Same as #90, this was in the background so I don't know how to replicate. I haven't even used CheckStyle on this project or set it up.

IntelliJ IDEA 14.0.3
CheckStyle-IDEA 4.12.0

    javax.swing.JLabel cannot be cast to org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowPanel
    java.lang.ClassCastException: javax.swing.JLabel cannot be cast to org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowPanel
	 at org.infernus.idea.checkstyle.actions.ScrollToSource.isSelected(ScrollToSource.java:37)
	 at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:64)
	 at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	 at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:383)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:703)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.a(GotoActionModel.java:698)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.access$000(GotoActionModel.java:660)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$MatchedValue.compareTo(GotoActionModel.java:180)
	 at com.intellij.ide.util.gotoByName.GotoActionModel.compare(GotoActionModel.java:376)
	 at java.util.TreeMap.compare(TreeMap.java:1291)
	 at java.util.TreeMap.put(TreeMap.java:538)
 	 at java.util.TreeSet.add(TreeSet.java:255)
 	 at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
 	 at java.util.TreeSet.addAll(TreeSet.java:312)
 	 at com.intellij.ide.util.gotoByName.GotoActionModel.sort(GotoActionModel.java:544)
	 at com.intellij.ide.actions.GotoActionAction$2.filter(GotoActionAction.java:83)
	 at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread$1$2.run(ChooseByNameBase.java:1573)
	 at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	 at java.awt.EventQueue.access$400(EventQueue.java:97)
	 at java.awt.EventQueue$3.run(EventQueue.java:697)
	 at java.awt.EventQueue$3.run(EventQueue.java:691)
	 at java.security.AccessController.doPrivileged(Native Method)
	 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	 at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	 at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

    java.lang.ClassCastException: javax.swing.JLabel cannot be cast to   org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowPanel
	 at org.infernus.idea.checkstyle.actions.ScrollToSource.isSelected(ScrollToSource.java:37)
	 at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:64)
	 at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	 at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:383)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:703)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.a(GotoActionModel.java:698)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.access$000(GotoActionModel.java:660)
	 at com.intellij.ide.util.gotoByName.GotoActionModel$MatchedValue.compareTo(GotoActionModel.java:180)
	 at com.intellij.ide.util.gotoByName.GotoActionModel.compare(GotoActionModel.java:376)
	 at java.util.TreeMap.compare(TreeMap.java:1291)
	 at java.util.TreeMap.put(TreeMap.java:538)
	 at java.util.TreeSet.add(TreeSet.java:255)
	 at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	 at java.util.TreeSet.addAll(TreeSet.java:312)
	 at com.intellij.ide.util.gotoByName.GotoActionModel.sort(GotoActionModel.java:544)
	 at com.intellij.ide.actions.GotoActionAction$2.filter(GotoActionAction.java:83)
	 at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread$1$2.run(ChooseByNameBase.java:1573)
	 at  com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	 at java.awt.EventQueue.access$400(EventQueue.java:97)
	 at java.awt.EventQueue$3.run(EventQueue.java:697)
	 at java.awt.EventQueue$3.run(EventQueue.java:691)
	 at java.security.AccessController.doPrivileged(Native Method)
	 at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	 at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	 at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jshiell** [comment]
Thanks for the report.

It looks like IDEA 14 may be querying button state even if you haven't activated the tool window. Which is problematic, as I believe tool windows are loaded lazily. I'll add a check for it anon this week.

**Comment by jshiell** [comment]
Released as 4.13.1. I've covered off a fair few cases - if you see any more, please just shout!
