### ISSUE TITLE
'Cannot load project' in Intellij 14.1.1

### ISSUE THREAD

**Issue by gerritwalther** [jshiell/checkstyle-idea#153]
I've installed Intellij 14.1.1 (Build 141.178) yesterday and with that version of intellij I'm getting an error from the checkstyle plugin.
`Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]`

Full stacktrace:
`[  33360]  ERROR - openapi.options.ConfigurableEP - org/infernus/idea/checkstyle/CheckStyleConfigurable : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] 
com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStyleConfigurable : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:316)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.options.ConfigurableEP$1.compute(ConfigurableEP.java:141)
	at com.intellij.openapi.options.ConfigurableEP$1.compute(ConfigurableEP.java:132)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:38)
	at com.intellij.openapi.options.ConfigurableEP.canCreateConfigurable(ConfigurableEP.java:183)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:41)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:54)
	at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:98)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:83)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen$IconsFreeActionGroup$1.actionPerformed(FlatWelcomeFrame.java:567)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: org/infernus/idea/checkstyle/CheckStyleConfigurable : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:462)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 30 more`

With Intellij 14.0.3 (Build 139.1117) it is still running.

The project I'm working on is still running with Java 1.6. Tell me if you need any further info.

**Comment by jshiell** [comment]
Dup of #142. You need to run IDEA on Java 8 - this is entirely separate from whatever JVM your project is using.

**Comment by gerritwalther** [comment]
Thats embarrassing. Didn't completely read the release notes and obviously didn't look into the closed issues. Thanks for your reply and sorry for wasting your time.

**Comment by jshiell** [comment]
No worries - this has bitten a few people, and it's nice and easy to solve :smile: It's a shame there's no way to indicate the JVM required in the plugin XML, really.

**Comment by gerritwalther** [comment]
I even knew the error (major.minor thing) years ago from earlier java version changes. It's really a shame that our customer still requires Java 6 (and not the latest version of 6). Anyway I've created a script to compile the project with Java 6 and Java 8 is the system default. Now everything works smooth again.

**Comment by jshiell** [comment]
Legacy requirements are always a pain, I fear. I'm really not looking forward to the next time I have to use Java 6 or 7 for a project.

While it sounds like you've a nice solution in place, for Google/future viewers of this you can also set environment variables to control the IDEA JDK without changes the standard ones - https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by gerritwalther** [comment]
I have done the opposite of what is suggested there. Added Java 8 as default and created a script called `ant` which sets the environment variable to the Java 6 JDK and then calls the real ant (yes, we still use ant in that project).
