### ISSUE TITLE
Error loading plugin on IntelliJ IDEA startup on my MacBook Pro with Maverick.

### ISSUE THREAD

**Issue by lordigon** [jshiell/checkstyle-idea#156]
I get this exception when, with an open project I enable this plugin and restart the IDE. Plugin version is 
4.14.1.
This is the logged exception:

2015-04-19 07:29:59,843 [   7071]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
2015-04-19 07:30:00,467 [   7695]   INFO - roject.impl.ProjectManagerImpl - com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA] 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:441)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:319)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$700(ProjectManagerImpl.java:82)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:629)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:623)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
	... 29 more
Caused by: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
	... 26 more
Caused by: java.lang.UnsupportedClassVersionError: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 32 more
2015-04-19 07:30:06,682 [  13910]   INFO - roject.impl.ProjectManagerImpl - com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA] 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:441)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:319)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$700(ProjectManagerImpl.java:82)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:629)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:623)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
	... 29 more
Caused by: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
	... 26 more
Caused by: java.lang.UnsupportedClassVersionError: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 32 more
2015-04-19 07:30:48,164 [  55392]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/META-INF/tapestry_5_3.xsd class=class com.intellij.javaee.ResourceRegistrarImpl, classLoader:null 
2015-04-19 07:31:17,227 [  84455]  ERROR - ctionCallback.TimedOutCallback - Typeahead request blocked 
com.intellij.openapi.wm.impl.FocusManagerImpl$16: Time: 30003
	at com.intellij.openapi.wm.impl.FocusManagerImpl.typeAheadUntil(FocusManagerImpl.java:797)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:291)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:178)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:372)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:340)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-04-19 07:31:17,229 [  84457]  ERROR - ctionCallback.TimedOutCallback - IntelliJ IDEA 14.1.1  Build #IU-141.178.9 
2015-04-19 07:31:17,229 [  84457]  ERROR - ctionCallback.TimedOutCallback - JDK: 1.6.0_65 
2015-04-19 07:31:17,229 [  84457]  ERROR - ctionCallback.TimedOutCallback - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-19 07:31:17,229 [  84457]  ERROR - ctionCallback.TimedOutCallback - Vendor: Apple Inc. 
2015-04-19 07:31:17,230 [  84458]  ERROR - ctionCallback.TimedOutCallback - OS: Mac OS X 
2015-04-19 07:31:17,230 [  84458]  ERROR - ctionCallback.TimedOutCallback - Last Action: ShowLog

**Comment by jshiell** [comment]
Dup of #142. TL;DR you need to run IDEA on JDK 8.
