### ISSUE TITLE
Problem loading configuration file - Unable to instantiate RedundantThrows

### ISSUE THREAD

**Issue by cfontes** [jshiell/checkstyle-idea#157]
Hi, I am having problems loading my project config file

It always displays this stack that follows.

I've googled a bit and it seams like this ```RedundantThrows``` was removed and cannot be in listed anymore. It's not listed on my config so I guess it might be in the plugin somewhere.

Cheers

```
org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The CheckStyle rules file could not be loaded.</b><br>cannot initialize module TreeWalker - Unable to instantiate RedundantThrows</html>
	at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAndShowMessage(CheckerFactory.java:231)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:185)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:97)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getChecker(CheckerFactory.java:79)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getChecker(CheckerFactory.java:44)
	at org.infernus.idea.checkstyle.ui.LocationDialogue.testLoadOfFile(LocationDialogue.java:198)
	at org.infernus.idea.checkstyle.ui.LocationDialogue.access$800(LocationDialogue.java:25)
	at org.infernus.idea.checkstyle.ui.LocationDialogue$NextAction.actionPerformed(LocationDialogue.java:243)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.infernus.idea.checkstyle.ui.LocationDialogue.setVisible(LocationDialogue.java:151)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$AddLocationAction.actionPerformed(CheckStyleConfigPanel.java:326)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:408)
	at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:403)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:433)
	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:70)
	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:247)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by jshiell** [comment]
I believe that was removed in one of the 6.x releases. Could you please attach your rules file?

**Comment by cfontes** [comment]
Here it is

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">

	<module name="TreeWalker">
		<module name="ArrayTypeStyle">
			<property name="severity" value="info" />
		</module>
		<module name="AvoidNestedBlocks">
			<property name="severity" value="info" />
		</module>
		<module name="AvoidStarImport">
			<property name="severity" value="warning" />
		</module>
		<module name="TodoComment">
			<property name="severity" value="info" />
		</module>
		<module name="ConstantName">
			<property name="severity" value="warning" />
		</module>
		<module name="DeclarationOrder">
			<property name="severity" value="warning" />
		</module>
		<module name="DefaultComesLast">
			<property name="severity" value="info" />
		</module>
		<module name="EmptyBlock">
			<property name="severity" value="warning" />
		</module>
		<module name="EmptyForIteratorPad">
			<property name="severity" value="info" />
		</module>
		<module name="EmptyStatement">
			<property name="severity" value="info" />
		</module>
		<module name="EqualsHashCode">
			<property name="severity" value="error" />
		</module>
		<module name="FinalClass">
			<property name="severity" value="info" />
		</module>
		<module name="FinalParameters">
			<property name="severity" value="info" />
		</module>
		<module name="HiddenField">
			<property name="severity" value="error" />
			<property name="ignoreConstructorParameter" value="true" />
			<property name="ignoreSetter" value="true" />
		</module>
		<module name="IllegalInstantiation">
			<property name="severity" value="error" />
		</module>
		<module name="Indentation">
			<property name="severity" value="warning" />
			<property name="basicOffset" value="4" />
		</module>
		<module name="InnerAssignment">
			<property name="severity" value="error" />
		</module>
		<module name="InterfaceIsType">
			<property name="severity" value="info" />
		</module>
		<module name="JavadocMethod">
			<property name="severity" value="warning" />
			<property name="suppressLoadErrors" value="true" />
		</module>
		<module name="JavadocType">
			<property name="severity" value="warning" />
		</module>
		<module name="LeftCurly">
			<property name="severity" value="warning" />
		</module>
		<module name="LineLength">
			<property name="severity" value="warning" />
			<property name="max" value="120" />
		</module>
		<module name="LocalFinalVariableName">
			<property name="severity" value="warning" />
		</module>
		<module name="LocalVariableName">
			<property name="severity" value="warning" />
		</module>
		<module name="MagicNumber">
			<property name="severity" value="error" />
		</module>
		<module name="MemberName">
			<property name="severity" value="warning" />
		</module>
		<module name="MethodLength">
			<property name="severity" value="error" />
			<property name="max" value="100" />
			<property name="countEmpty" value="false" />
		</module>
		<module name="MethodName">
			<property name="severity" value="warning" />
		</module>
		<module name="MissingSwitchDefault">
			<property name="severity" value="info" />
		</module>
		<module name="ModifierOrder">
			<property name="severity" value="info" />
		</module>
		<module name="NeedBraces">
			<property name="severity" value="warning" />
		</module>
		<module name="NoWhitespaceAfter">
			<property name="severity" value="info" />
		</module>
		<module name="NoWhitespaceBefore">
			<property name="severity" value="info" />
		</module>
		<module name="OneStatementPerLine">
			<property name="severity" value="info" />
		</module>
		<module name="OperatorWrap">
			<property name="severity" value="info" />
		</module>
		<module name="PackageName">
			<property name="severity" value="warning" />
			<property name="format" value="^br.com.cielo.[a-z]+(\.[a-zA-Z_][a-zA-Z0-9_]*)*$" />
		</module>
		<module name="ParameterName">
			<property name="severity" value="warning" />
		</module>
		<module name="ParenPad">
			<property name="severity" value="info" />
		</module>
		<module name="RedundantImport">
			<property name="severity" value="info" />
		</module>
		<module name="RedundantModifier">
			<property name="severity" value="info" />
		</module>
		<module name="RedundantThrows">
			<property name="severity" value="info" />
			<property name="suppressLoadErrors" value="true" />
		</module>
		<module name="RightCurly">
			<property name="severity" value="warning" />
		</module>
		<module name="SimplifyBooleanExpression">
			<property name="severity" value="info" />
		</module>
		<module name="SimplifyBooleanReturn">
			<property name="severity" value="info" />
		</module>
		<module name="StaticVariableName">
			<property name="severity" value="warning" />
		</module>
		<module name="TypeName">
			<property name="severity" value="warning" />
		</module>
		<module name="TypecastParenPad">
			<property name="severity" value="info" />
			<property name="tokens" value="RPAREN,TYPECAST" />
		</module>
		<module name="UncommentedMain">
			<property name="severity" value="info" />
		</module>
		<module name="UnusedImports">
			<property name="severity" value="info" />
		</module>
		<module name="UpperEll">
			<property name="severity" value="info" />
		</module>
		<module name="VisibilityModifier">
			<property name="severity" value="info" />
		</module>
		<module name="WhitespaceAfter">
			<property name="severity" value="info" />
		</module>
		<module name="IllegalThrows">
			<property name="severity" value="warning" />
		</module>
		<module name="EqualsAvoidNull">
			<property name="severity" value="error" />
		</module>
		<module name="ClassTypeParameterName">
			<property name="severity" value="warning" />
		</module>
		<module name="MethodTypeParameterName">
			<property name="severity" value="warning" />
		</module>
		<module name="IllegalImport">
			<property name="severity" value="warning" />
		</module>
		<module name="ParameterNumber">
			<property name="severity" value="warning" />
		</module>
		<module name="MethodParamPad">
			<property name="severity" value="info" />
		</module>
		<module name="NestedIfDepth">
			<property name="severity" value="error" />
			<property name="max" value="2" />
		</module>
		<module name="MultipleVariableDeclarations">
			<property name="severity" value="info" />
		</module>
		<module name="NestedForDepth">
			<property name="severity" value="error" />
			<property name="max" value="2" />
		</module>
		<module name="RequireThis">
			<property name="severity" value="warning" />
		</module>
	</module>

	<module name="StrictDuplicateCode">
		<property name="severity" value="warning" />
	</module>

	<module name="UniqueProperties">
		<property name="severity" value="warning" />
	</module>

	<module name="Translation">
		<property name="severity" value="warning" />
	</module>
</module>
```

**Comment by jshiell** [comment]
You've got a RedundantThrows check at line 136.
```
   <module name="RedundantThrows">
            <property name="severity" value="info" />
            <property name="suppressLoadErrors" value="true" />
        </module>
```
This was removed as of CheckStyle 6.2, as per https://github.com/checkstyle/checkstyle/issues/473. If you remove this it should work.
