### ISSUE TITLE
Failed scan on multi-module project

### ISSUE THREAD

**Issue by sdaschner** [jshiell/checkstyle-idea#190]
If I run the checkstyle plugin (on a Maven multi-module project) it fails with following Event Log:

```
CheckStylePluginException: An error occurred while scanning a file.: An error occurred during a file scan.
```

The stack trace of the `CheckStylePluginException`:

```
An error occurred while scanning a file.: An error occurred during a file scan.
org.infernus.idea.checkstyle.exception.CheckStylePluginException: An error occurred during a file scan.
 at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
 at org.infernus.idea.checkstyle.checker.CheckFilesThread.run(CheckFilesThread.java:43)
Caused by: java.io.FileNotFoundException: target\cachefile (The system cannot find the path specified)
 at java.io.FileOutputStream.open(Native Method)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
 at com.puppycrawl.tools.checkstyle.PropertyCacheFile.persist(PropertyCacheFile.java:135)
 at com.puppycrawl.tools.checkstyle.TreeWalker.destroy(TreeWalker.java:485)
 at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:287)
 at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
 at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
 at org.infernus.idea.checkstyle.checker.FileScanner.lambda$checkPsiFile$12(FileScanner.java:90)
 at org.infernus.idea.checkstyle.checker.FileScanner$$Lambda$64/23551238.apply(Unknown Source)
 at java.util.Optional.map(Optional.java:215)
 at org.infernus.idea.checkstyle.checker.FileScanner.checkPsiFile(FileScanner.java:90)
 at org.infernus.idea.checkstyle.checker.FileScanner.run(FileScanner.java:42)
 at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
 at org.infernus.idea.checkstyle.checker.CheckFilesThread.runFileScanner(CheckFilesThread.java:30)
 at org.infernus.idea.checkstyle.checker.AbstractCheckerThread.processFilesForModuleInfoAndScan(AbstractCheckerThread.java:113)
 at org.infernus.idea.checkstyle.checker.CheckFilesThread.run(CheckFilesThread.java:39) 
```

What is the `target/cachefile` about?

**Comment by sdaschner** [comment]
Tested on the `4.19.1` version.

**Comment by jshiell** [comment]
No idea what the `target/cachefile` is - entirely new to me. Could you please attach your rules file?  Thanks.

**Comment by sdaschner** [comment]
Thanks for your quick response!
I currently don't have access to the project, but that may sound like the error is our side...
I'll let you know if the error persists with a modified configuration.

**Comment by jshiell** [comment]
Thanks :smile:
