### ISSUE TITLE
Error when loading checkstyle.xml from remote url

### ISSUE THREAD

**Issue by clausfod** [jshiell/checkstyle-idea#191]
```xml
org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be loaded.</b><br>unable to parse configuration stream<br>The file has been blacklisted for 60s.</html>
                      at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAndShowMessage(CheckerFactory.java:183)
                      at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:139)
                      at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:84)
                      at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:63)
                      at org.infernus.idea.checkstyle.checker.CheckerFactory.verify(CheckerFactory.java:44)
                      at org.infernus.idea.checkstyle.ui.LocationDialogue.attemptLoadOfFile(LocationDialogue.java:198)
                      at org.infernus.idea.checkstyle.ui.LocationDialogue.access$800(LocationDialogue.java:24)
                      at org.infernus.idea.checkstyle.ui.LocationDialogue$NextAction.actionPerformed(LocationDialogue.java:250)
                      at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
                      at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
                      at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
                      at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
                      at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
                      at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
                      at java.awt.Component.processMouseEvent(Component.java:6525)
                      at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
                      at java.awt.Component.processEvent(Component.java:6290)
                      at java.awt.Container.processEvent(Container.java:2234)
                      at java.awt.Component.dispatchEventImpl(Component.java:4881)
                      at java.awt.Container.dispatchEventImpl(Container.java:2292)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
                      at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
                      at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
                      at java.awt.Container.dispatchEventImpl(Container.java:2278)
                      at java.awt.Window.dispatchEventImpl(Window.java:2750)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
                      at java.awt.EventQueue.access$500(EventQueue.java:97)
                      at java.awt.EventQueue$3.run(EventQueue.java:702)
                      at java.awt.EventQueue$3.run(EventQueue.java:696)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
                      at java.awt.EventQueue$4.run(EventQueue.java:724)
                      at java.awt.EventQueue$4.run(EventQueue.java:722)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
                      at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
                      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
                      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
                      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
                      at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
                      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
                      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
                      at java.awt.Dialog.show(Dialog.java:1084)
                      at java.awt.Component.show(Component.java:1654)
                      at java.awt.Component.setVisible(Component.java:1606)
                      at java.awt.Window.setVisible(Window.java:1014)
                      at java.awt.Dialog.setVisible(Dialog.java:1005)
                      at org.infernus.idea.checkstyle.ui.LocationDialogue.setVisible(LocationDialogue.java:151)
                      at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$AddLocationAction.actionPerformed(CheckStyleConfigPanel.java:324)
                      at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:399)
                      at org.infernus.idea.checkstyle.ui.CheckStyleConfigPanel$ToolbarAction.run(CheckStyleConfigPanel.java:394)
                      at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:433)
                      at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:70)
                      at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:247)
                      at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
                      at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
                      at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
                      at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
                      at java.awt.Component.processEvent(Component.java:6290)
                      at java.awt.Container.processEvent(Container.java:2234)
                      at java.awt.Component.dispatchEventImpl(Component.java:4881)
                      at java.awt.Container.dispatchEventImpl(Container.java:2292)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
                      at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
                      at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
                      at java.awt.Container.dispatchEventImpl(Container.java:2278)
                      at java.awt.Window.dispatchEventImpl(Window.java:2750)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
                      at java.awt.EventQueue.access$500(EventQueue.java:97)
                      at java.awt.EventQueue$3.run(EventQueue.java:702)
                      at java.awt.EventQueue$3.run(EventQueue.java:696)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
                      at java.awt.EventQueue$4.run(EventQueue.java:724)
                      at java.awt.EventQueue$4.run(EventQueue.java:722)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
                      at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
                      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
                      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
                      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
                      at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
                      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
                      at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
                      at java.awt.Dialog.show(Dialog.java:1084)
                      at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
                      at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
                      at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
                      at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
                      at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
                      at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
                      at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
                      at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
                      at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
                      at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
                      at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
                      at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
                      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
                      at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
                      at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
                      at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
                      at java.awt.Component.processMouseEvent(Component.java:6525)
                      at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
                      at java.awt.Component.processEvent(Component.java:6290)
                      at java.awt.Container.processEvent(Container.java:2234)
                      at java.awt.Component.dispatchEventImpl(Component.java:4881)
                      at java.awt.Container.dispatchEventImpl(Container.java:2292)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
                      at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
                      at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
                      at java.awt.Container.dispatchEventImpl(Container.java:2278)
                      at java.awt.Window.dispatchEventImpl(Window.java:2750)
                      at java.awt.Component.dispatchEvent(Component.java:4703)
                      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
                      at java.awt.EventQueue.access$500(EventQueue.java:97)
                      at java.awt.EventQueue$3.run(EventQueue.java:702)
                      at java.awt.EventQueue$3.run(EventQueue.java:696)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
                      at java.awt.EventQueue$4.run(EventQueue.java:724)
                      at java.awt.EventQueue$4.run(EventQueue.java:722)
                      at java.security.AccessController.doPrivileged(Native Method)
                      at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                      at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
                      at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
                      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
                      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
                      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                      at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                      at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by clausfod** [comment]
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://jee-qa/jee-qa/trunk/checkstyle/configuration_1_2.dtd">

<module name="Checker">

    
    <module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="lf" />
    </module>

    
    <module name="FileLength">
        <property name="max" value="1500" />
    </module>
    <module name="FileTabCharacter" />

    <module name="Translation" />

    <module name="TreeWalker">
        <property name="cacheFile" value="target/checkstyle-cachefile" />

        
        <module name="JavadocType">
            <property name="scope" value="public" />
            <property name="tokens" value="INTERFACE_DEF, CLASS_DEF" />
        </module>

        
        <module name="ConstantName" />
        <module name="LocalVariableName" />
        <module name="LocalFinalVariableName" />
        <module name="MemberName" />
        <module name="MethodName" />
        <module name="PackageName" />
        <module name="ParameterName" />
        <module name="StaticVariableName" />
        <module name="TypeName" />

        
        <module name="AvoidStaticImport" />
        <module name="IllegalImport" />
        <module name="RedundantImport" />
        <module name="UnusedImports" />
        <module name="AvoidStarImport">
            <property name="excludes" value="java.*, javax.*" />
        </module>
        <module name="ImportOrder">
            <property name="groups" value="java, javax, *" />
            <property name="ordered" value="true" />
            <property name="separated" value="true" />
            <property name="option" value="above" />
        </module>

        
        <module name="MethodParamPad" />
        <module name="NoWhitespaceAfter" />
        <module name="NoWhitespaceBefore" />
        <module name="ParenPad" />
        <module name="TypecastParenPad" />
        <module name="WhitespaceAfter" />
        <module name="WhitespaceAround" />
        <module name="Indentation" />
        <module name="GenericWhitespace" />

        
        <module name="ModifierOrder" />
        <module name="RedundantModifier" />

        
        <module name="EmptyBlock">
            <property name="option" value="text" />
        </module>
        <module name="LeftCurly" />
        <module name="RightCurly" />
        <module name="AvoidNestedBlocks" />

        
        <module name="CovariantEquals" />
        <module name="EmptyStatement" />
        <module name="EqualsAvoidNull" />
        <module name="EqualsHashCode" />

        
        <module name="IllegalInstantiation" />
        <module name="HiddenField">
            <property name="tokens" value="VARIABLE_DEF" />
        </module>
        <module name="MissingSwitchDefault" />
        <module name="InnerAssignment" />
        <module name="MagicNumber">
            <property name="tokens" value="NUM_DOUBLE, NUM_FLOAT" />
            <property name="ignoreNumbers" value="0, 0.5, 0.75, 1" />
        </module>
        <module name="ModifiedControlVariable" />
        <module name="SimplifyBooleanExpression" />
        <module name="SimplifyBooleanReturn" />
        <module name="StringLiteralEquality" />
        <module name="NestedTryDepth">
            <property name="max" value="3" />
        </module>
        <module name="IllegalCatch">
            <property name="illegalClassNames"
                value="java.lang.Throwable, java.lang.Error" />
        </module>
        <module name="IllegalThrows" />
        <module name="PackageDeclaration" />
        <module name="MultipleStringLiterals">
            <property name="allowedDuplicates" value="3" />
            <property name="ignoreStringsRegexp" value=".{0,12}" />
        </module>
        <module name="MultipleVariableDeclarations" />

        <module name="SuperClone" />

        <module name="DeclarationOrder" />
        <module name="ExplicitInitialization" />
        <module name="DefaultComesLast" />
        <module name="FallThrough" />

        
        <module name="HideUtilityClassConstructor" />
        <module name="NeedBraces">
            <property name="tokens"
                value="LITERAL_DO, LITERAL_FOR, LITERAL_WHILE" />
        </module>
        <module name="ThrowsCount">
            <property name="max" value="3" />
        </module>

        
        <module name="BooleanExpressionComplexity" />
        <module name="ClassDataAbstractionCoupling">
            <property name="max" value="15" />
        </module>
        <module name="ClassFanOutComplexity">
            <property name="max" value="30" />
        </module>
        <module name="CyclomaticComplexity">
            <property name="max" value="20" />
        </module>
        <module name="NPathComplexity">
            <property name="max" value="350" />
        </module>
        <module name="JavaNCSS">
            <property name="methodMaximum" value="150" />
        </module>
        <module name="ParameterNumber">
            <property name="max" value="7" />
        </module>

        
        <module name="Regexp">
            <property name="format" value="System\.(out|err)\.println" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value="System.out.println() - never write to the console - use logging instead" />
        </module>
        <module name="Regexp">
            <property name="format" value="\.printStackTrace\(\)" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value=" printStackTrace() never write to the console - use logging instead" />
        </module>
        <module name="Regexp">
            <property name="format" value="Class\.forName" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value=" do you want to use Class.forName - use context classloader instead" />
        </module>
        <module name="Regexp">
            <property name="format" value="Place description here" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value=" Place description here - is an autogenerated comment - are noise - remove it" />
        </module>
        <module name="Regexp">
            <property name="format"
                value="Header: |Revision: |@version|@since" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value="Header: |Revision: |@version|@since - are noise - remove it" />
        </module>
        <module name="Regexp">
            <property name="format"
                value="User:|Date:|Time:|Created by IntelliJ IDEA.|Copyright " />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value=" User:|Date:|Time:|Created by IntelliJ IDEA.|Copyright are autogenerated comments - are noise - remove it" />
        </module>
        <module name="Regexp">
            <property name="format" value=" Cloneable" />
            <property name="illegalPattern" value="true" />
            <property name="message"
                value="Cloneable is broken by design - use copy constructors instead" />
        </module>

        <module name="ArrayTypeStyle" />
        <module name="UncommentedMain" />
        <module name="UpperEll" />

        <module name="LineLength">
            <property name="max" value="144" />
        </module>

        <module name="MethodLength">
            <property name="countEmpty" value="false" />
            <property name="max" value="50" />
        </module>

        <module name="AnonInnerLength">
            <property name="max" value="40" />
        </module>
    </module>
    <module name="SuppressionFilter">
        <property name="file"
            value="${basedir}/config/checkstyle_suppressions.xml" />
    </module>
</module>
