### ISSUE TITLE
CheckStyle threw an exception when scanning

### ISSUE THREAD

**Issue by thatGuy0923** [jshiell/checkstyle-idea#198]
```
CheckStyle threw an exception when scanning: ProcessHeap.java: Exception was thrown while processing /var/folders/_z/xvrj6l0d2z9ckr_ypn8wmpkm0000gn/T/csi-13de424a-3082-433d-bc98-a18bbf62aeac/src/ProcessHeap.java
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing /var/folders/_z/xvrj6l0d2z9ckr_ypn8wmpkm0000gn/T/csi-13de424a-3082-433d-bc98-a18bbf62aeac/src/ProcessHeap.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:23)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:66)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$15(CheckStyleInspection.java:81)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$51/513037776.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:81)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:57)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$37/74248043.call(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /var/folders/_z/xvrj6l0d2z9ckr_ypn8wmpkm0000gn/T/csi-13de424a-3082-433d-bc98-a18bbf62aeac/src/ProcessHeap.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	... 13 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred during the analysis of file /var/folders/_z/xvrj6l0d2z9ckr_ypn8wmpkm0000gn/T/csi-13de424a-3082-433d-bc98-a18bbf62aeac/src/ProcessHeap.java.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:218)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 14 more
Caused by: /var/folders/_z/xvrj6l0d2z9ckr_ypn8wmpkm0000gn/T/csi-13de424a-3082-433d-bc98-a18bbf62aeac/src/ProcessHeap.java:105:9: expecting EOF, found 'index'
	at antlr.Parser.match(Parser.java:211)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:210)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:468)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:200)
	... 16 more

**Comment by thatGuy0923** [comment]
Can anyone help me with this issue?

**Comment by jshiell** [comment]
Checkstyle failed to parse your class. It's harmless, you were probably just editing it at the time. I'll have a look and see why the CS exception isn't being suppressed.

**Comment by fjank** [comment]
Checkstyle-IDEA was working nice'n'dandy before the latest release. Now this happens all the time when editing files. Same stacktrace as thatGuy0923.

**Comment by jshiell** [comment]
Probably means the Checkstyle devs changed how errors are thrown. They do this every so often, and as their official line is that 'Checkstyle is only to be run on syntactically valid files' it's left to the rest of us to clean up after them.

I'll try get it fixed later this week.

**Comment by jshiell** [comment]
Checkstyle 6.12 started nested its `CheckstyleException` instances, which broke detection of parse problems. Should be sorted in 4.21.1. Thanks for the reports.
