### ISSUE TITLE
Read Access Exception in IntelliJ 15.0.1 & plugin version 4.21.1

### ISSUE THREAD

**Issue by ErikCrombag** [jshiell/checkstyle-idea#200]
I get the following exception as soon as I turn on my checkstyle configuration:
```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 17,4,main] 7979735
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 15.0.1#IC-143.382.35, eap:false,6,main] 32360534
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1047)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.moduleDependencyComparator(ModuleManagerImpl.java:544)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:115)
	at org.infernus.idea.checkstyle.CheckStyleInspection.moduleOf(CheckStyleInspection.java:123)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:70)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:57)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$32/26923123.call(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by jshiell** [comment]
This appears to be related to the changes for #192; module lookup apparently can't take place on a background thread.

Should be fixed in 4.21.2. Thanks for the report.
