### ISSUE TITLE
CheckStyle-IDEA exception while editing code - ArrayIndexOutOfBoundsException at com.puppycrawl.tools.checkstyle.api.FileText.get

### ISSUE THREAD

**Issue by cjr8020** [jshiell/checkstyle-idea#201]
Intellij IDEA 15.0.1 Community Edition
CheckStyle-IDEA 4.21.2

Error message:
```
CheckStyle threw an exception when scanning: Blah.java: Exception was thrown while processing C:\Users\blah\AppData\Local\Temp\csi-e88defaf-e094-422a-86bd-43809be1a2c4\src\main\java\com\blah\Blah.java

Details:
CheckStyle threw an exception when scanning: Blah.java: Exception was thrown while processing C:\Users\blah\AppData\Local\Temp\csi-e88defaf-e094-422a-86bd-43809be1a2c4\src\main\java\com\blah\Blah.java
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing C:\Users\blah\AppData\Local\Temp\csi-e88defaf-e094-422a-86bd-43809be1a2c4\src\main\java\com\blah\Blah.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:23)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:66)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$15(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$47/5112878.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:58)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$31/9528280.call(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing C:\Users\blah\AppData\Local\Temp\csi-e88defaf-e094-422a-86bd-43809be1a2c4\src\main\java\blah\Blah.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2147483647
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:324)
	at com.puppycrawl.tools.checkstyle.api.FileContents.getLine(FileContents.java:249)
	at com.puppycrawl.tools.checkstyle.api.Check.getLine(Check.java:186)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkExpressionSubtree(AbstractExpressionHandler.java:424)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkChildren(AbstractExpressionHandler.java:400)
	at com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler.checkIndentation(BlockParentHandler.java:279)
	at com.puppycrawl.tools.checkstyle.checks.indentation.MethodDefHandler.checkIndentation(MethodDefHandler.java:72)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:292)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 14 more
```

**Comment by jshiell** [comment]
Looking at the stack trace it's most likely (although not certainly) a bug in Checkstyle. I'll try push a new version of the plugin with the latest version of Checkstyle (6.13) later this week, in the hope it's been fixed already.

**Comment by jshiell** [comment]
Released 4.22 with Checkstyle 6.13. Hopefully it turn out to have been fixed already :smile:

**Comment by cjr8020** [comment]
wow, thanks!
Updated to 4.22.. will report

**Comment by cjr8020** [comment]
still occurs with 4.22
Thanks

**Comment by jshiell** [comment]
Bugger. Could you please attach the source in question, and your rules file?

**Comment by cjr8020** [comment]
source: any java class showing errors in IDEA as you're editing it ..
rules file: a modified version of google_checks.
[google_checks_modified.txt](https://github.com/jshiell/checkstyle-idea/files/61523/google_checks_modified.txt)

**Comment by cjr8020** [comment]
source: apparently, editing a JDBI DAO interface does it every time.. 
[GmrOrgDao.txt](https://github.com/jshiell/checkstyle-idea/files/61698/GmrOrgDao.txt)

**Comment by cjr8020** [comment]
another source example
[GmrOrgMapper.txt](https://github.com/jshiell/checkstyle-idea/files/61706/GmrOrgMapper.txt)

**Comment by jshiell** [comment]
Smashing, thanks. Your comment of 'any java class showing errors in IDEA as you're editing it' is actually hugely helpful - Checkstyle does't support syntactically incorrect files, so we have to try and catch such errors and eat them. They're usually wrapped but it looks like this one may not be. I'll try have a look this weekend.

**Comment by vrozov** [comment]
Also running into the same issue
```
CheckStyle threw an exception when scanning: InputStream.java: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-75b6c013-f076-413e-aba2-20787d67a56f/src/test/java/com/datatorrent/netlet/benchmark/netty/InputStream.java
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-75b6c013-f076-413e-aba2-20787d67a56f/src/test/java/com/datatorrent/netlet/benchmark/netty/InputStream.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:23)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:66)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$15(CheckStyleInspection.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:58)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /var/folders/vx/mfh0w1ld4p374hd749qg47j40000gp/T/csi-75b6c013-f076-413e-aba2-20787d67a56f/src/test/java/com/datatorrent/netlet/benchmark/netty/InputStream.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2147483647
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:324)
	at com.puppycrawl.tools.checkstyle.api.FileContents.getLine(FileContents.java:249)
	at com.puppycrawl.tools.checkstyle.api.Check.getLine(Check.java:186)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkExpressionSubtree(AbstractExpressionHandler.java:424)
	at com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler.checkChildren(AbstractExpressionHandler.java:400)
	at com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler.checkIndentation(BlockParentHandler.java:279)
	at com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck.visitToken(IndentationCheck.java:292)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 12 more
```

**Comment by jshiell** [comment]
I've made version 4.22.1 of the plugin a little more tolerant of exceptions coming from Checkstyle while editing, so hopefully this'll knock it on the head. Please shout if I'm wrong - thanks!
