### ISSUE TITLE
NPE while editing code

### ISSUE THREAD

**Issue by twbecker** [jshiell/checkstyle-idea#203]
I've seen this a couple of times now. Haven't yet narrowed down exactly how to reproduce but I get the exception popup with the following stacktrace:
```
CheckStyle threw an exception when scanning: TopicHandler.java: Exception was thrown while processing /tmp/csi-d2e323be-3314-45ce-bd85-7c501f0b2d21/src/main/java/com/digitalsmiths/ffs/streamjobs/util/tasks/TopicHandler.java
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing /tmp/csi-d2e323be-3314-45ce-bd85-7c501f0b2d21/src/main/java/com/digitalsmiths/ffs/streamjobs/util/tasks/TopicHandler.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:23)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:66)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$15(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$46/1638840377.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$14(CheckStyleInspection.java:58)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$36/388825893.call(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /tmp/csi-d2e323be-3314-45ce-bd85-7c501f0b2d21/src/main/java/com/digitalsmiths/ffs/streamjobs/util/tasks/TopicHandler.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	... 13 more
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck$ClassDesc.access$100(FinalClassCheck.java:111)
	at com.puppycrawl.tools.checkstyle.checks.design.FinalClassCheck.visitToken(FinalClassCheck.java:87)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 14 more
```

**Comment by jshiell** [comment]
Thanks - looks like it's coming from Checkstyle, so the most likely cause is unparsable source and Checkstyle changing just how it wraps these exceptions. Looks like I've 2-3 of these to fix over Christmas :smile:

**Comment by jshiell** [comment]
I've made version 4.22.1 of the plugin a little more tolerant of exceptions coming from Checkstyle while editing, so hopefully this'll knock it on the head. Please shout if I'm wrong - thanks!
