### ISSUE TITLE
Checkstyle tries to parse xml files when using "Run checkstyle on all modified files"

### ISSUE THREAD

**Issue by grzesuav** [jshiell/checkstyle-idea#215]
Hi,

when I use "Run checkstyle on all modified files" and I have changes in xml files, checkstyle quit with error "unexpected token: <" so it seems it tries to parse xml file just as java file which causes whole analysis to fail. It should fail to check only file with parsing problem, not cancel whole analysis.

**Comment by jshiell** [comment]
Hmm, there is a filter in there for non-Java files, so something is probably amiss. I'll try have a butchers this weekend. Thanks for the report!

**Comment by grzesuav** [comment]
I have enabled parsing of non-java files, but still I expect that if parsing of one file will fail this will not break whole analysis.

**Comment by jshiell** [comment]
Depends on the error. Checkstyle doesn't have great support for third party tools, so we're stuck with heuristics to work out if exceptions are valid (e.g. parse) or not (e.g. NPEs) or either (also NPEs at times), and this changes every few versions. So I'll have a look and see if it's a case we can catch, but parsing non-Java files is always going to be risky and liable to do silly things.

**Comment by mkordas** [comment]
@grzesuav can you post your stacktrace?  Generally Checkstyle shouldn't try to execute Java-only checks for non Java files. You may also try limiting file extensions to `.java` for TreeWalker

**Comment by grzesuav** [comment]
An error occurred while scanning a file.: An error occurred during a file scan.
org.infernus.idea.checkstyle.exception.CheckStylePluginParseException: An error occurred during a file scan.
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:43)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:84)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:391)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file <PATH-TO-SPRING-XML>Test-context.xml.
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$13(ScanFiles.java:192)
	at org.infernus.idea.checkstyle.checker.ScanFiles$$Lambda$74/402446.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:192)
	at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:150)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:76)
	... 7 more
Caused by: <PATH-TO-SPRING-XML>Test-context.xml:1:1: unexpected token: <
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:180)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:453)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:185)
	... 17 more

**Comment by jshiell** [comment]
I've been having a look at this this morning. The bad news: the plugin's behaviour is as intended and won't be changed.

The reason the error breaks the entire scan is that we do not pass each file to Checkstyle's checker one by one, but as a batch. Hence an exception will break the whole batch.  I'm not willing to reduce performance by removing the batch to catch edge cases like this. Given the exception is correctly detected as a parse exception from Checkstyle, I'm happy with the compromise chosen.

More interestingly, I couldn't reproduce this - after turning on _scan non-Java files_ I was unable to find a XML file that'd break Checkstyle. In all of them it returned a sensible result (and even warned me about missing newlines), which backs up @mkordas's comment and suggests this really is an edge case. I tried both with the XML (and DTD) files in the project, and also with some example Springer bean defs I swiped from Google.

This was all with the latest release code (4.25.1 from memory) and Checkstyle 6.15.

I'd suggest coming up with a reproducible case via the Checkstyle CLI and submitted an issue to [Checkstyle](http://github.com/checkstyle/checkstyle) itself - they're always very responsive to bugs over there, as demonstrated by @mkordas's kind response here.

**Comment by mkordas** [comment]
@grzesuav `TreeWalker` should never try to analyze non-java files. Can you try playing with `fileExtensions` property (http://checkstyle.sourceforge.net/config.html#Properties) and check if it reoccurs? Ideally would be to reproduce it by CLI with your current config and report as bug to Checkstyle.
