### ISSUE TITLE
IDEA 15.0.4 cannot start after install checkstyle plugin...

### ISSUE THREAD

**Issue by bhui** [jshiell/checkstyle-idea#219]
```java
Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.IllegalArgumentException: MALFORMED
    at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
    at java.util.zip.ZipFile.getZipEntry(ZipFile.java:567)
    at java.util.zip.ZipFile.access$900(ZipFile.java:61)
    at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:525)
    at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:500)
    at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:481)
    at com.intellij.util.lang.JarLoader.buildData(JarLoader.java:110)
    at com.intellij.util.lang.ClassPath.initLoader(ClassPath.java:241)
    at com.intellij.util.lang.ClassPath.initLoaders(ClassPath.java:201)
    at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:157)
    at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:116)
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:204)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.ide.Bootstrap.main(Bootstrap.java:36)
    at com.intellij.idea.Main.main(Main.java:91)
```

checkstyle plugin version is 
```xml
<idea-plugin version="2" url="https://github.com/jshiell/checkstyle-idea">
  <id>CheckStyle-IDEA</id>
  <name>CheckStyle-IDEA</name>
  <resource-bundle>org.infernus.idea.checkstyle.CheckStyleBundle</resource-bundle>
  <description>
        
&lt;p&gt;
    This plugin provides both real-time and on-demand scanning
    of Java files with CheckStyle 6.15 from within IDEA.
&lt;/p&gt;
        
    </description>
  <version>4.26.0</version>
  <idea-version since-build="141.178"/>
  <vendor url="https://infernus.org/" email="james@infernus.org">James Shiell</vendor>
  <depends>com.intellij.modules.java</depends>
  <change-notes>
```

**Comment by bhui** [comment]
I hava re install IDEA 15 .... Now it's OK

**Comment by jshiell** [comment]
No idea why this said it was this plugin, as that exception trace looks like core IDEA. In any case, glad it's OK now.
