### ISSUE TITLE
Unexpected ast

### ISSUE THREAD

**Issue by gsf-greece** [jshiell/checkstyle-idea#228]
I was refactoring some legacy code and I was changing some String name[][] to String[][] name when this occured:

    CheckStyle threw an exception when scanning: MySqlBaseDao.java: Exception was thrown while processing (tmp file here)/MySqlBaseDao.java
    org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing (tmp file here)/MySqlBaseDao.java
      at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:44)
      at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:33)
      at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:70)
      at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:44)
      at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$1(CheckStyleInspection.java:86)
      at java.util.Optional.map(Optional.java:215)
      at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:86)
      at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:58)
      at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:394)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing (tmp file here)/MySqlBaseDao.java
      at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:250)
      at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:190)
      at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:68)
      ... 10 more
    Caused by: java.lang.IllegalStateException: unexpected ast syntaxEXPR[265x16]
      at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.getArrayDeclaratorPreviousElement(NoWhitespaceAfterCheck.java:265)
      at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.getWhitespaceFollowedNode(NoWhitespaceAfterCheck.java:154)
      at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.visitToken(NoWhitespaceAfterCheck.java:129)
      at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
      at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:478)
      at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:305)
      at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
      at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
      at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:270)
      at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:240)
      ... 12 more

I changed many similar variables before I saw that exception so It's not happening all the time. Anyway I thought I should report it.

**Comment by jshiell** [comment]
Thanks for the report!

Checkstyle isn't intended for use on files being edited, so the plugin does some logic to try and determine if an exception should be suppressed or not. Every so often a new one pops up - it looks like this is one of them. I'll have a look at the logic and extend it to cover this case.

**Comment by jshiell** [comment]
This should be fixed in 4.28.1.
