### ISSUE TITLE
CheckStyle threw an exception when scanning: .gitignore: Couldn't create Checker from Checkout

### ISSUE THREAD

**Issue by BorzdeG** [jshiell/checkstyle-idea#240]
When you delete the configuration file for the selected plug-in Checkstyle without removing it from its plug-in settings, we get an error:

CheckStyle threw an exception when scanning: .gitignore: Couldn't create Checker from Checkout
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Couldn't create Checker from Checkout
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:68)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:47)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:85)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:58)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:330)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: File does not exist: _CUT_PROJECT_PATH_/checkstyle-configuration.xml
	at org.infernus.idea.checkstyle.model.FileConfigurationLocation.resolveFile(FileConfigurationLocation.java:84)
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.getProperties(ConfigurationLocation.java:94)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.addEclipseCsProperties(CheckerFactory.java:94)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:81)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:61)
	... 8 more

**Comment by jshiell** [comment]
Thanks for the report. I'll have a look, but it won't be immediately due to my country committing economic and political suicide.

**Comment by jshiell** [comment]
This should be in the next release, hopefully this weekend - thanks for your help and contributions!
