### ISSUE TITLE
StringIndexOutOfBoundsException thrown by latest plugin version

### ISSUE THREAD

**Issue by huxi** [jshiell/checkstyle-idea#282]
This keeps popping up in IDEA.

macOS 10.12.2
IDEA 2016.3.2
Checkstyle-IDEA 4.35.0

```
String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.infernus.idea.checkstyle.model.ConfigurationLocationFactory.create(ConfigurationLocationFactory.java:110)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.deserialiseLocation(CheckStyleConfiguration.java:166)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentSkipListMap$EntrySpliterator.forEachRemaining(ConcurrentSkipListMap.java:3518)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.configurationLocations(CheckStyleConfiguration.java:150)
	at org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowPanel.configurationChanged(CheckStyleToolWindowPanel.java:232)
	at org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowPanel.<init>(CheckStyleToolWindowPanel.java:120)
	at org.infernus.idea.checkstyle.toolwindow.CheckStyleToolWindowFactory.createToolWindowContent(CheckStyleToolWindowFactory.java:15)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:568)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.a(ToolWindowManagerImpl.java:460)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow(ToolWindowManagerImpl.java:463)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$4.run(ToolWindowManagerImpl.java:420)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:92)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:993)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:92)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:993)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:92)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:993)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:92)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:993)
	at com.intellij.openapi.wm.impl.CommandProcessor.b(CommandProcessor.java:92)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:72)
	at com.intellij.openapi.wm.impl.CommandProcessor.flush(CommandProcessor.java:46)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.f(ToolWindowManagerImpl.java:541)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$3700(ToolWindowManagerImpl.java:90)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$InitToolWindowsActivity.a(ToolWindowManagerImpl.java:2474)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:435)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:338)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:321)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:193)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:403)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:189)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:613)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy46.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:340)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:338)
	at com.intellij.idea.IdeaApplication.b(IdeaApplication.java:193)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:69)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jshiell** [comment]
Thanks for the report - looks like something is corrupt in the settings, and the plugin isn't handling it. I'll have a look at this as soon as the PR for #199 is sorted.

**Comment by jshiell** [comment]
The encoded configuration location is definitely malformed in some way. Could you please attach your settings, if possible, so I can verify the fix? If you're using a directly base project structure, the settings will be in `.idea/checkstyle-idea.xml`.

Thanks very much.

**Comment by huxi** [comment]
I upgraded to IDEA 2016.3.3 in the meantime and recreated the project files in the process.

Unfortunately, I can't reproduce the problem anymore. I'll holler if I stumble over it again, though.

Chances are that I broke the configuration myself, somehow, because I was more or less frantically trying to get a `suppressions.xml` file working which the plugin wouldn't pick up. I may have missed that `location-x` also contains the name separated by `:` while editing the config manually.

Sorry for causing you trouble...

I think I got it now but I'm still thoroughly confused about the difference between `LOCAL_FILE` and `PROJECT_RELATIVE`. They behave exactly the same for me.

The project I'm talking about is https://github.com/huxi/sulky/
I generate the project files using `./gradlew idea`

The generated `sulky.ipr` contains the following section after I manually configure the Checkstyle-plugin:

```xml
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:sulky-checkstyle" />
        <entry key="location-0" value="CLASSPATH:/sun_checks.xml:The default Checkstyle rules" />
        <entry key="location-1" value="LOCAL_FILE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:sulky absolute" />
        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:sulky-checkstyle" />
        <entry key="property-1.baseDir" value="$PROJECT_DIR$" />
        <entry key="property-1.configDir" value="$PROJECT_DIR$/config/checkstyle" />
        <entry key="property-2.baseDir" value="$PROJECT_DIR$" />
        <entry key="property-2.configDir" value="$PROJECT_DIR$/config/checkstyle" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
        <entry key="thirdparty-classpath" value="" />
      </map>
    </option>
  </component>
```

One thing that's confusing me is that `LOCAL_FILE` also contains the `$PRJ_DIR$` placeholder in both `location` and `property` while I expected it to contain absolute paths instead...

The other thing that caused me to stumble was `$PRJ_DIR$` vs. `$PROJECT_DIR$`.

Anyway, feel free to close this issue.

I just tried to shed some light on the source of my confusion because that feedback might actually be useful for you. As some kind of compensation for the original issue...

**Comment by jshiell** [comment]
No worries, and thanks very much for the context! This certainly uncovered cases where we would throw an exception instead of handling the broken descriptor, so the fix was definitely worthwhile - thanks for your help!

`LOCAL_FILE` and `PROJECT_RELATIVE` should differ in that `LOCAL_FILE` is a file on a local filesystem, whereas `PROJECT_RELATIVE` is a file on the local filesystem that is always referenced relative to the project file (intended for shared project files where people may keep the projects in difference locations). Hence moving the project file will result in the former breaking but not the latter. If you're not moving about, they're identical. That's from memory, mind - I reserve the right to be wrong ;-) 

Thanks again, and the fix that is done will be in the next release (hopefully this weekend).
