### ISSUE TITLE
ConnectException: Operation timed out

### ISSUE THREAD

**Issue by vbauer** [jshiell/checkstyle-idea#285]
I use checkstyle configuration file from internal network resource, so when I launch Intellij IDEA outside this network I usually get an internal error:

```
Couldn't read URL: https://some-internal-github-installation.ru/raw/example-organization/exmple-repository/master/src/main/resources/checkstyle/checkstyle.xml: Operation timed out
java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.infernus.idea.checkstyle.model.HTTPURLConfigurationLocation.asBytes(HTTPURLConfigurationLocation.java:73)
	at org.infernus.idea.checkstyle.model.HTTPURLConfigurationLocation.resolveFile(HTTPURLConfigurationLocation.java:40)
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.getProperties(ConfigurationLocation.java:94)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.addEclipseCsProperties(CheckerFactory.java:94)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:81)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:61)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:47)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:88)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:61)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:331)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

As I understand there are 2 solutions to resolve this problem:
* to hide this error or show it as warning
* to cache previous version of checkstyle configuration file somewhere

**Comment by jshiell** [comment]
Thanks for the report. The HTTP support has always been a little raw I'm afraid. Both your suggestions seem very fair - I'll try and take a look at this after I've got the next version out (which will hopefully be this weekend).

**Comment by jshiell** [comment]
In 5.0.1 IOExceptions while loading the rule files should generate a warning, rather than causing an IDE exception. The feedback isn't particularly detailed at present, but should be substantially less annoying. Please shout if it doesn't fix your exact problem!

**Comment by vbauer** [comment]
Thank you very much for information and quick response!
