### ISSUE TITLE
Loading checkstyle config failed with internal error

### ISSUE THREAD

**Issue by wolfey** [jshiell/checkstyle-idea#291]
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Checkstyle-IDEA plugin version 5.1.0

Loading this file :[ergon-rules-2.0.xml.txt](https://github.com/jshiell/checkstyle-idea/files/747118/ergon-rules-2.0.xml.txt)

gives the following error:
```
internal error - A CheckstyleInternalObject passed to the service layer could not be processed. Expected: org.infernus.idea.checkstyle.service.entities.HasChecker, actual: org.infernus.idea.checkstyle.service.entities.CheckerWithConfig [interfaces: org.infernus.idea.checkstyle.csapi.CheckstyleInternalObject, org.infernus.idea.checkstyle.service.entities.HasChecker, org.infernus.idea.checkstyle.service.entities.HasCsConfig]. This is a bug. Either the wrong object (or null) was passed to the service layer, or a CheckstyleInternalObject was cached for too long and the service layer's classloader has changed.
org.infernus.idea.checkstyle.exception.CheckstyleVersionMixException: internal error - A CheckstyleInternalObject passed to the service layer could not be processed. Expected: org.infernus.idea.checkstyle.service.entities.HasChecker, actual: org.infernus.idea.checkstyle.service.entities.CheckerWithConfig [interfaces: org.infernus.idea.checkstyle.csapi.CheckstyleInternalObject, org.infernus.idea.checkstyle.service.entities.HasChecker, org.infernus.idea.checkstyle.service.entities.HasCsConfig]. This is a bug. Either the wrong object (or null) was passed to the service layer, or a CheckstyleInternalObject was cached for too long and the service layer's classloader has changed.
    at org.infernus.idea.checkstyle.service.cmd.OpDestroyChecker.<init>(OpDestroyChecker.java:23)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.destroyChecker(CheckstyleActionsImpl.java:57)
    at org.infernus.idea.checkstyle.checker.CheckStyleChecker.destroy(CheckStyleChecker.java:45)
    at org.infernus.idea.checkstyle.checker.CachedChecker.destroy(CachedChecker.java:48)
    at org.infernus.idea.checkstyle.checker.CheckerFactoryCache.destroyChecker(CheckerFactoryCache.java:77)
    at java.util.HashMap$Values.forEach(HashMap.java:980)
    at org.infernus.idea.checkstyle.checker.CheckerFactoryCache.lambda$invalidate$2(CheckerFactoryCache.java:70)
    at org.infernus.idea.checkstyle.checker.CheckerFactoryCache.writeToCache(CheckerFactoryCache.java:102)
    at org.infernus.idea.checkstyle.checker.CheckerFactoryCache.invalidate(CheckerFactoryCache.java:69)
    at org.infernus.idea.checkstyle.actions.ResetLoadedRulesFiles.actionPerformed(ResetLoadedRulesFiles.java:22)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jshiell** [comment]
Thanks for the report. Could you please tell me which version of Checkstyle were you using at the time?

**Comment by wolfey** [comment]
I think it was the newest version 7.5

**Comment by jshiell** [comment]
Thanks - I'll try and take a look at this over the weekend!

**Comment by tsjensen** [comment]
Did you make any changes to the Checkstyle version around when the bug happened?

**Comment by wolfey** [comment]
I updated IntelliJ and the plugin just before. I may have tried to change the checkstyle version.

**Comment by tsjensen** [comment]
Would you be able to provide simple instructions on how to cause the problem?
I tried:
- start IntelliJ (plugin previously configured for Checkstyle 6.12.1)
- press scan project &rarr; no problem
- change Checkstyle version to 6.13
- press scan project &rarr; no problem
- press sync button &rarr; still no problem ...

**Comment by jshiell** [comment]
Hi @wolfey - does this problem still occur in 5.1.3 (which has the changes from @tsjensen referenced above)? Thank you.

**Comment by wolfey** [comment]
Hi @jshiell, @tsjensen, I can not reproduce the error in 5.1.3, so I am assuming the fix worked. Thank you!
