### ISSUE TITLE
NoSuchMethodError fatal error

### ISSUE THREAD

**Issue by Roman-Skripka** [jshiell/checkstyle-idea#294]
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I have an "IDE fatal errors" in Checkstyle-IDEA plugin v5.1.1:
`org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.trace(SLF4JLocationAwareLog.java:99)
	at org.apache.commons.beanutils.BeanUtilsBean.convert(BeanUtilsBean.java:1078)
	at org.apache.commons.beanutils.BeanUtilsBean.convertForCopy(BeanUtilsBean.java:1095)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:435)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:202)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:164)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:58)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:23)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:121)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:42)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:44)
`
It worked fine about one or two weeks ago.

**Comment by tsjensen** [comment]
Looks like the commons-logging provided by JetBrains and the commons-logging used by Checkstyle have diverged. We currently exclude commons-logging from the Checkstyle classpath so that Checkstyle uses the commons-logging provided by IDEA.
Does it work when you switch to an older version of Checkstyle, maybe 7.4 or 7.2? Which version did you use?

**Comment by Roman-Skripka** [comment]
Version 7.5 is my current one and gives the error above. 7.4 works the same way. 
Version 7.2 gives a bit more detailed message:
`CheckStyle threw an exception when scanning: ***.java: Couldn't create Checker from ****-checks
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Couldn't create Checker from ****-checks
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:63)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:89)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:331)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.infernus.idea.checkstyle.exception.CheckStylePluginException: Could not load configuration
	at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:151)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:75)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:57)
	... 7 more
Caused by: org.infernus.idea.checkstyle.exception.CheckstyleServiceException: Error executing command 'OpCreateChecker': internal error - Failed to call com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration()
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:138)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:42)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:44)
Caused by: org.infernus.idea.checkstyle.exception.CheckstyleServiceException: internal error - Failed to call com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration()
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.callLoadConfiguration(OpLoadConfiguration.java:184)
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.execute(OpLoadConfiguration.java:136)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.loadConfig(OpCreateChecker.java:69)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:53)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:23)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:121)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.callLoadConfiguration(OpLoadConfiguration.java:178)
	... 8 more
Caused by: java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:131)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.endElement(ConfigurationLoader.java:483)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.puppycrawl.tools.checkstyle.api.AbstractLoader.parseInputSource(AbstractLoader.java:96)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:152)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:231)
	... 13 more`

**Comment by tsjensen** [comment]
Thanks. If it happens with older versions, too, then it can't be just an updated Checkstyle dependency. Gotta keep looking. It might help if you could share your rules file?

**Comment by Roman-Skripka** [comment]
@tsjensen http://pastebin.com/AznwAhLL + http://pastebin.com/PZ04JGe8

**Comment by jshiell** [comment]
Looking at the latest POMs it seems Checkstyle is using SLF4J now. From memory, IDEA used to use commons-logging to Log4J, and poking about the IDEA lib folder that seems to hold.

However, IDEA also now has a bridge from SLF4J to Log4j. Google suggests this was commonly seen between SLF 1.5 and 1.6. Both IDEA and CS are using 1.7.x though. No bright ideas as yet, I fear.

**Comment by tsjensen** [comment]
Hmm ... I just tried your files, Checkstyle 7.5 activated, but everything worked fine. :confounded:
 I had to remove the `optional` property from the `SuppressionFilter` module, though.
What are your steps to reproduce the problem?

**Comment by jshiell** [comment]
More specifically, this error seems to be coming out of the commons-logging -> SLF4j bridge. Damned if I can find where this is being included, though.

@tsjensen I've found these problems really hard to reproduce in the past, as the classpath seems to differ slightly depending on platform 😢 

@Roman-Skripka what platform are you running on?

**Comment by Roman-Skripka** [comment]
@tsjensen to reproduce I just launch the idea with some opened .java file. If there is no opened files it doesn't throw error. (nothing to analyze :) )
@jshiell Linux Mint 18.1 cinnamon x64

**Comment by jshiell** [comment]
The only instances I've found of this class are in the Maven plugin.

@Roman-Skripka is the Maven plugin enabled; and are you seeing this in a Maven project?

**Comment by Roman-Skripka** [comment]
@jshiell yes, it's maven 3 project.

**Comment by jshiell** [comment]
Current update - no luck reproducing with Maven projects. I suspect this'll be something subtle about the loading order, given the classpath elements involved. Will keep trying.

**Comment by jshiell** [comment]
An experiment - could you please try the test version below? I've just altered it to include SLF4J and the bridges (JCL -> SLF, SLF -> Log4j), which should force everything into the plugin classpath. Perhaps. Given my failure to reproduce, it's worth try, anyway. Thanks very much!

https://dl.dropboxusercontent.com/u/5423904/CheckStyle-IDEA-5.1.1.zip

**Comment by jshiell** [comment]
I've now released this changed in 5.1.2, along with a properties fix. Can you please let us know if it fixes/changed/doesn't do a damned thing to your problem? Thanks.

**Comment by Roman-Skripka** [comment]
@jshiell thanks, will check and report back on Monday.

**Comment by Roman-Skripka** [comment]
@jshiell Sorry for delay, I caught a cold and was unable to verify. Just installed a new version and... it works! Thank you guys!
