### ISSUE TITLE
Cannot init CheckStyle-IDEA component state: Cyclic dependency: [class org.infernus.idea.checkstyle.CheckstyleProjectService]

### ISSUE THREAD

**Issue by BorzdeG** [jshiell/checkstyle-idea#327]
IntelliJ IDEA 2017.2 EAP
Build #IU-172.3317.6, built on July 4, 2017
IntelliJ IDEA EAP User
Expiration date: August 3, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Checkstyle-IDEA Plugin: 5.8.0

`Cannot init CheckStyle-IDEA component state: Cyclic dependency: [class org.infernus.idea.checkstyle.CheckstyleProjectService]
org.picocontainer.defaults.CyclicDependencyException: Cyclic dependency: [class org.infernus.idea.checkstyle.CheckstyleProjectService]
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:75)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getInstance(CheckstyleProjectService.java:117)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.readCheckstyleVersion(CheckStyleConfiguration.java:358)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.toDto(CheckStyleConfiguration.java:332)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:311)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:27)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:329)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getInstance(CheckStyleConfiguration.java:476)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.<init>(CheckstyleProjectService.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getInstance(CheckstyleProjectService.java:117)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.readCheckstyleVersion(CheckStyleConfiguration.java:358)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.toDto(CheckStyleConfiguration.java:332)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:311)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.loadState(CheckStyleConfiguration.java:27)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:329)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getInstance(CheckStyleConfiguration.java:476)
	at org.infernus.idea.checkstyle.CheckStylePlugin.<init>(CheckStylePlugin.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:284)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:278)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:532)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$200(ProjectManagerImpl.java:70)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:479)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:476)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:603)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jshiell** [comment]
Can you please give me context? What version of the plugin are you using? What OS? What version of IDEA? Anything else relevant?

**Comment by BorzdeG** [comment]
Yes, I added a cap to the issue version of the plug-in and IDEA

**Comment by BorzdeG** [comment]
The error occurred after today's update of the plug-in to version 5.8.0 in the same version of IDEA

**Comment by jshiell** [comment]
Thanks. I fear we don't support EAP versions of IDEA. Does it occur on 2017.1.x?

**Comment by tsjensen** [comment]
This is at least an untested case, where he does not have Checkstyle version information in his persistent config (hasn't upgraded in a long while or at least not changed the config). I tried a quick fix with #328.

**Comment by jshiell** [comment]
Thanks @BorzdeG for the report and @tsjensen for the extremely snappy fix! I'm just doing a quick sanity check and will aim to get a release out ASAP (5.8.1).
