### ISSUE TITLE
 Cannot download. Received fatal alert: SSL handshake_failure

### ISSUE THREAD

**Issue by satybald** [jshiell/checkstyle-idea#329]
I'm not able to install the plugin from the jetbrains plugin repository. Looks like certificate issue. How is it possible to install it locally? 

```
Plugin CheckStyle-IDEA was not installed: Cannot download 'https://plugins.jetbrains.com/pluginManager/?action=download&id=CheckStyle-IDEA&build=IC-163.7743.44&uuid=209d26d6-5145-46eb-97b5-7d16a88dacc2': Received fatal alert: handshake_failure

```
IntelliJ IDEA 2016.3
Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

```
![checkstyleplugin](https://user-images.githubusercontent.com/2764630/28083013-67c8dcc0-6674-11e7-8d86-5ba1ad4d796f.png)

Exception from the log.
````
2017-07-11 20:04:43,451 [25120838]   WARN - Settings.impl.PluginDownloader - Cannot download 'https://plugins.jetbrains.com/pluginManager/?action=download&id=CheckStyle-IDEA&build=IC-163.7743.44&uuid=209d26d6-5145-46eb-97b5-7d16a88dacc2': Received fatal alert: handshake_failure 
java.io.IOException: Cannot download 'https://plugins.jetbrains.com/pluginManager/?action=download&id=CheckStyle-IDEA&build=IC-163.7743.44&uuid=209d26d6-5145-46eb-97b5-7d16a88dacc2': Received fatal alert: handshake_failure
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:353)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:245)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:242)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:402)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:396)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.downloadPlugin(PluginDownloader.java:242)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:142)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:235)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:127)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:66)
	at com.intellij.ide.plugins.PluginManagerMain$5.run(PluginManagerMain.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2662)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2584)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1770)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:473)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:277)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:286)
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:349)
	... 25 more

````

**Comment by tsjensen** [comment]
You may download from here and install from disk:
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea

**Comment by jshiell** [comment]
Thanks @tsjensen 😄

**Comment by satybald** [comment]
awesome! thanks, folks!
