### ISSUE TITLE
Not working with OpenJDK 9

### ISSUE THREAD

**Issue by gianluca-nitti** [jshiell/checkstyle-idea#346]
If I run IntelliJ with OpenJDK 9 (Java 9 is [general availability](http://mail.openjdk.java.net/pipermail/announce/2017-September/000230.html) since a couple of days), this plugin appears not to work.

In fact, I get an "IDE error" dialog which reports that this exception has been thrown in the CheckStyle-IDEA plugin:
```
Cannot get state after load
java.lang.NullPointerException
	at org.infernus.idea.checkstyle.VersionListReader.readSupportedVersions(VersionListReader.java:89)
	at org.infernus.idea.checkstyle.VersionListReader.<init>(VersionListReader.java:43)
	at org.infernus.idea.checkstyle.VersionListReader.<init>(VersionListReader.java:38)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.buildDefaultConfig(CheckStyleConfiguration.java:93)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getState(CheckStyleConfiguration.java:313)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getState(CheckStyleConfiguration.java:41)
	at com.intellij.configurationStore.StateGetter.close(StorageBaseEx.kt:53)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:332)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at org.infernus.idea.checkstyle.CheckStyleConfiguration.getInstance(CheckStyleConfiguration.java:493)
	at org.infernus.idea.checkstyle.CheckStylePlugin.<init>(CheckStylePlugin.java:60)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:284)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:278)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:533)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$200(ProjectManagerImpl.java:70)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:479)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:476)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:602)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
Then I don't get CheckStyle warnings while editing Java files in the IDE, and if I try to open the CheckStyle tool window from the `View > Tool windows > CheckStyle`, the panel which pops up is empty (i.e. there isn't the usual UI to use CheckStyle).

**Comment by tsjensen** [comment]
Quick analysis:
It seems we have an actual Java 9 related bug. That piece of the code tries to determine the Java version via `Runtime.class.getPackage().getSpecificationVersion()`. Since Java 9, one can simply call `Runtime.version()` ... but since we want to be compatible with Java 8, maybe we should rather do `System.getProperty("java.version")`.

The fix would be in line 85 of the `VersionListReader`. No sure if I'll get around to it this weekend, though.

**Comment by jshiell** [comment]
Thanks @tsjensen - I haven't even been able to get IDEA 2017.2 to start under JDK9 on OS X - it just hangs once the bar is full on the splash screen (although it still responds to quit events).

@gianluca-nitti thanks for the reports - I've put a test build on Dropbox, which will hopefully fix this, although I haven't tested it due to the problem mentioned above. Could you please try it if you have a moment? Assuming all is well, I'll release it once we've confirmation that #345 is also fixed in this build. Thank you!

https://www.dropbox.com/s/cfkqnx14eb4zx5y/CheckStyle-IDEA-5.10.1.zip?dl=0

**Comment by gianluca-nitti** [comment]
Thank you @tsjensen and @jshiell for the very quick replies.

I tried your build from Dropbox by uninstalling the Checkstyle-IDEA version I already had and installing the zip with the "Install plugin from file" button, then tested on both the OpenJDK versions (8 and 9). Seems like it works; I can open the tool window and see the list of Checkstyle problems in the current file by clicking the green play button. A quite curious behavior I noticed, however, is that with OpenJDK 8 the warnings also get highlighted as I type, while with OpenJDK 9 this functionality seems missing. With both of them I can get the warning list in the tool window, though.

**Comment by jshiell** [comment]
I've release this, since it seems to fix this issue for a couple of people. Thanks for your help.

The warnings is more likely to be core IDEA, as the highlighting is part of that. We just implement an interface to return a list of errors. But I'll have a look once JDK9 support is working on the Mac.
