### ISSUE TITLE
Could not add new configuration file (reports same error as #352, but just happens on windows)

### ISSUE THREAD

**Issue by geekShaw86** [jshiell/checkstyle-idea#367]
Hi there:
Android Studio 3.0.1
Gradle 4.1
Checkstyle 7.8.2
checkstyle-idea 5.12.1

When adding new configuration file, it reported error like this:

org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be parsed.</b><br>cannot initialize module TreeWalker - Property 'maxLineLength' in module LeftCurly does not exist, please check the documentation<br>The file has been blacklisted for 60s.</html>
 at org.infernus.idea.checkstyle.checker.CheckerFactory.lambda$blacklistAndShowMessage$0(CheckerFactory.java:196)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAnd(CheckerFactory.java:220)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAndShowMessage(CheckerFactory.java:192)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.blacklistAndShowMessage(CheckerFactory.java:236)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:146)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:75)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:57)
 at org.infernus.idea.checkstyle.checker.CheckerFactory.verify(CheckerFactory.java:44)
 at org.infernus.idea.checkstyle.ui.LocationDialogue.attemptLoadOfFile(LocationDialogue.java:205)
 at org.infernus.idea.checkstyle.ui.LocationDialogue.access$900(LocationDialogue.java:35)
 at org.infernus.idea.checkstyle.ui.LocationDialogue$NextAction.actionPerformed(LocationDialogue.java:252)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
 at java.awt.Component.processMouseEvent(Component.java:6541)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Co

I have found the same problem in issue#352, but there is something weired: I got no problem using the same version of Android Studio(3.0.1) and Gradle(4.1) and Checkstyle(7.8.2) and checkstyle-idea(5.12.1) on another MacBook, it seems only happens on Windows(win10), so do you have any idea about this? Any help will be appreciated, thanks in advance.
PS： I have tried to comment that maxLineLength property, but it doesn't work, still reports the same error.

**Comment by jshiell** [comment]
Hi,

What version of Checkstyle do you have selected in the preferences? This property was removed in 8.2 (http://checkstyle.sourceforge.net/releasenotes.html) so if you select Checkstyle 8.1 or below I'd expect it'd be fine.

Cheers,
James

**Comment by Xinima** [comment]
Thanks for your reply, and I used Checkstyle 7.8.2. And it works just fine on MacBook pro, but no luck on Windows(Win10)

**Comment by jshiell** [comment]
That's curious, as that error message is just proxying back a Checkstyle error. We never generate errors of that type.

The bad news is that I don't use Windows, so if it only occurs on Windows then I fear this might be stuck until that changes. Sorry.

**Comment by jshiell** [comment]
I've been playing with trying to reproduce this anyway, and have found one bug which may contribute to it.

It looks like changing the Checkstyle version does not take any affect any you press `Okay` or `Apply`. Hence if you change the version and immediately try to add a new file, it'll be validated against the previously selected version of Checkstyle.

You can work around this by changing the version of Checkstyle, hitting `Apply`, and then importing the new file.

Might this fit your use case?

**Comment by jshiell** [comment]
Closed due to no further updates.
