### ISSUE TITLE
Possibility to override idea.plugins.path-Property for checkstyle plugin only

### ISSUE THREAD

**Issue by chwoerz** [jshiell/checkstyle-idea#368]
I'd like to be able to override the default plugins-path provided by IntelliJ.

Currently I get an error: Could not determine plugin directory

That's because, the variable idea.plugins.path points to the "wrong" directory. 

In my case, I need to install Checkstyle into the IntelliJ main-folder itself and not into the .IntelliJIdea-directory, because we need to be able to distribute the IDEA with some default-plugins installed.

Also I can't change the idea.plugins.path-variable to point to another directory than .IntelliJIdea, because if the user wants to install specific plugins, the have to be in the .IntelliJIdea-folder. Otherwise, after an update of the IDE, the plugins will be lost.

Is there a way to to that already?

**Comment by jshiell** [comment]
Are you getting an error from the plugin or from IDEA? As we rely entirely on IDEA for the plugin environment; we don't do anything special AFAIK.

If there's something specific to the plugin we could try gentrify it, potentially, but my suspicion is this is more likely a matter for core IDEA.

**Comment by chwoerz** [comment]
I'm getting an error in the Event-Log. But it's strange, because with Version 5.7 it works, but not with 5.10.2. But I'm only getting an Error if I use version 5.15. If I use 5.10.2 the only error I get is "The uiles file is blacklisted for seconds due to an error."

The error occurs on line 187 in the CheckstyleClassLoader, because the needed plugin directory is not found. In my opinion, this could be fixed, if the user would be allowed to set a property to specify the checkstyle-plugin-path by himself, if the PathManager doesn't find the directory.

**Comment by chwoerz** [comment]
To reproduce the error, do the following steps:
1. Use IntelliJ 2017.3
2. Install the plugin as usual.
3. Open ./IntelliJIdea/plugins and cut the Checkstyle-IDEA-Folder
4. Paste the folder into bin/plugins/
5. Start IntelliJ
6. Try to run a Check. The error will occur.

**Comment by jshiell** [comment]
Thanks - I seem to be able to reproduce via the OS X version of the above:
```
mv ~/Library/Application\ Support/IntelliJIdea2017.3/CheckStyle-IDEA /Applications/IntelliJ\ IDEA.app/Contents/plugins
open /Applications/IntelliJ\ IDEA.app
```
The following error pops up in the event log:
```
11:19	The scan failed due to an exception: Could not determine plugin directory
			org.infernus.idea.checkstyle.exception.CheckStylePluginException: Could not determine plugin directory
			at org.infernus.idea.checkstyle.CheckstyleClassLoader.getBasePath(CheckstyleClassLoader.java:184)
			at org.infernus.idea.checkstyle.CheckstyleClassLoader.buildClassLoader(CheckstyleClassLoader.java:87)
			at org.infernus.idea.checkstyle.CheckstyleClassLoader.<init>(CheckstyleClassLoader.java:68)
			at org.infernus.idea.checkstyle.CheckstyleProjectService$1.call(CheckstyleProjectService.java:75)
			at org.infernus.idea.checkstyle.CheckstyleProjectService$1.call(CheckstyleProjectService.java:71)
			at org.infernus.idea.checkstyle.CheckstyleProjectService.getCheckstyleInstance(CheckstyleProjectService.java:102)
			at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:43)
```
This definitely seems plugin specific so I'll try and have a look over Christmas and see if I can find what's amiss.

**Comment by jshiell** [comment]
This should be fixed in 5.16.0 - IDEA's API exposes the pre-install plugin dir so we can try looking there if we can't find it in the normal plugin dir. It certainly fixes the case I produced above.

**Comment by Alok-Sharma** [comment]
Facing this issue with 5.16.1 and 5.16.0 and Android Studio 3.0.1 on OS X

`org.infernus.idea.checkstyle.exception.CheckStylePluginException: Could not determine plugin directory
	at org.infernus.idea.checkstyle.CheckstyleClassLoader.getBasePath(CheckstyleClassLoader.java:169)
	at org.infernus.idea.checkstyle.CheckstyleClassLoader.buildClassLoader(CheckstyleClassLoader.java:90)
	at org.infernus.idea.checkstyle.CheckstyleClassLoader.<init>(CheckstyleClassLoader.java:65)
	at org.infernus.idea.checkstyle.CheckstyleProjectService$1.call(CheckstyleProjectService.java:75)
	at org.infernus.idea.checkstyle.CheckstyleProjectService$1.call(CheckstyleProjectService.java:71)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getCheckstyleInstance(CheckstyleProjectService.java:102)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:43)`

**Comment by jshiell** [comment]
This was pretty dependent on the layout, and has only been tested with IDEA (as I don't use AS). Can you describe a case to reproduce please?
