### ISSUE TITLE
plugin replaces $PRJ_DIR incorrectly in .idea/checkstyle-idea.xml

### ISSUE THREAD

**Issue by dsilvasc** [jshiell/checkstyle-idea#374]
I have the following .idea/checkstyle-idea.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="checkstyle-version" value="8.2" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="property-2.config_loc" value="" />
        <entry key="scan-before-checkin" value="false" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>
```

When I open my intellij project, I get the following error in intellij's event log:

```
10:57	Properties could not be read from the Checkstyle configuration file

10:57	The Checkstyle rules file could not be read

10:58	Properties could not be read from the Checkstyle configuration file
...
```

That last one repeats several times.

If I then go to the checkstyle plugin preferences panel, I get a loading spinner that never ends.  When I then cancel that dialog, I get this IDE error:

```
Unable to test configuration properties for changes
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Unable to test configuration properties for changes
	at org.infernus.idea.checkstyle.PluginConfigDto.locationsAreEqual(PluginConfigDto.java:123)
	at org.infernus.idea.checkstyle.PluginConfigDto.hasChangedFrom(PluginConfigDto.java:109)
	at org.infernus.idea.checkstyle.CheckStyleConfigurable.isModified(CheckStyleConfigurable.java:61)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:169)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:391)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:385)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:373)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:194)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.lambda$select$0(ConfigurableEditor.java:247)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:121)
	at com.intellij.ui.CardLayoutPanel.lambda$null$0(CardLayoutPanel.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$submit$6(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: File does not exist: /Users/danielsilva/src/content-platform/../other-project/config/checkstyle/checkstyle.xml
	at org.infernus.idea.checkstyle.model.FileConfigurationLocation.resolveFile(FileConfigurationLocation.java:76)
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.getProperties(ConfigurationLocation.java:104)
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.propertiesHaveChanged(ConfigurationLocation.java:330)
	at org.infernus.idea.checkstyle.model.ConfigurationLocation.hasChangedFrom(ConfigurationLocation.java:322)
	at org.infernus.idea.checkstyle.PluginConfigDto.locationsAreEqual(PluginConfigDto.java:119)
	... 68 more
```

I don't understand why the plugin is replacing `.../other-project/` for $PRJ_DIR.

**Comment by jshiell** [comment]
Neither do I. `PRJ_DIR` is substituted for the project path from IDEA in [FileConfigurationLocation](https://github.com/jshiell/checkstyle-idea/blob/aed031977136c51bed703f580d9d7096aff56140/src/main/java/org/infernus/idea/checkstyle/model/FileConfigurationLocation.java#L245). This relies entire on the IDEA API to get this value, which is why it seems curious that in your case it doesn't match IDEA's `PROJECT_DIR`variable.

I'll have a think about this and a poke around at the weekend, as frankly I'm at a bit of a loss. It's not even a bit of code that's been modified recently.

**Comment by dsilvasc** [comment]
I upgraded to the latest version of the plugin today, and now when I open my project the plugin changes my config like this:

```diff
$ git diff
diff --git a/.idea/checkstyle-idea.xml b/.idea/checkstyle-idea.xml
index 259ef0b..0830f20 100644
--- a/.idea/checkstyle-idea.xml
+++ b/.idea/checkstyle-idea.xml
@@ -3,13 +3,13 @@
   <component name="CheckStyle-IDEA">
     <option name="configuration">
       <map>
-        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
+        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/../other-project/config/checkstyle/checkstyle.xml:content-platform" />
         <entry key="checkstyle-version" value="8.2" />
         <entry key="copy-libs" value="false" />
+        <entry key="last-active-plugin-version" value="5.16.3" />
         <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
         <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
-        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
-        <entry key="property-2.config_loc" value="" />
+        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/../other-project/config/checkstyle/checkstyle.xml:content-platform" />
         <entry key="scan-before-checkin" value="false" />
         <entry key="scanscope" value="JavaOnlyWithTests" />
         <entry key="suppress-errors" value="false" />
```

**Comment by jshiell** [comment]
That's odd. The only change made was the addition of the `last-active-plugin-version`. It's been months since the relative path construction was changed in any way. What was your previous version?

**Comment by dsilvasc** [comment]
I thought I was on the latest version before the upgrade.

Here's a small project that fails in the same way for me:
https://github.com/dsilvasc/repro-checkstyle-idea-374

There's nothing unusual about the project, so I think you're right that something's wrong with IntelliJ.

**Comment by dsilvasc** [comment]
argh... I'm sorry, I see the problem now, and it was my user error.

I found just now a path variable in ~/Library/Preferences/IdeaIC2017.3/options/path.macros.xml named PRJ_DIR pointing to the other project.  That clearly shouldn't be there.  I don't remember when I set it or why, but that's where the wrong substitution came from.

**Comment by dsilvasc** [comment]
Looks like that load error came from .idea/workspace.xml

```
...
  <component name="GradleLocalSettings">
    ...
    <option name="projectSyncType">
      <map>
        <entry key="$PRJ_DIR$" value="PREVIEW" />
        <entry key="$PROJECT_DIR$/../some-project" value="PREVIEW" />
        <entry key="$PROJECT_DIR$" value="RE_IMPORT" />
      </map>
    </option>
  </component>
...
```

I deleted .idea/workspace.xml and now that error is gone too.

**Comment by jshiell** [comment]
That is fascinating - I didn't even really you could affect it through such a path - nice spot! Good to hear things are working now 👍
