### ISSUE TITLE
The checks crashes, promising the error in EventLog, nothing there

### ISSUE THREAD

**Issue by jzaruba** [jshiell/checkstyle-idea#383]
Since yesterday my checkstyle keeps crashing, I am getting following error:
_The scan failed due to an error - please see the event log for more information_
...yet there is nothing in the EventLog.

**Comment by jshiell** [comment]
I'll need more details than that, as nothing changed with regards to the plugin yesterday. What's does the IDEA log file show?

**Comment by jzaruba** [comment]
I did not realize there is a log-file I can check, thanks for the hint. :)

So the issue seems to be an invalid java source file. I happened to have a generated Java-file template in my main/src/.../somethingGenerated folder.

Could you make the plugin report such errors into the EventLog please?

`2018-02-24 12:12:01,563 [ 537239]   WARN - a.checkstyle.checker.ScanFiles - An error occurred while scanning a file. 
org.infernus.idea.checkstyle.exception.CheckStylePluginParseException: NoViableAltException occurred during the analysis of file C:\Users\543829705\workspace\dev.appl.ib.cbl\application\src\main\resources\mwf\xmlMappings\generated\gatewayInterface.java.
    at org.infernus.idea.checkstyle.service.ExceptionWrapper.wrap(ExceptionWrapper.java:33)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:132)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
    at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)
    at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$5(ScanFiles.java:196)
    at java.util.Optional.map(Optional.java:215)
    at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:196)
    at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:155)
    at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:79)
    at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:31)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:338)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file C:\Users\543829705\workspace\dev.appl.ib.cbl\application\src\main\resources\mwf\xmlMappings\generated\gatewayInterface.java.
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:199)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:75)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)
    at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)
    at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
    ... 13 more
Caused by: C:\Users\543829705\workspace\dev.appl.ib.cbl\application\src\main\resources\mwf\xmlMappings\generated\gatewayInterface.java:1:5: unexpected token: Queue
    at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
    at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:446)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:179)
    ... 21 more`

**Comment by jshiell** [comment]
A very fair request - done in 5.18.1 😄  Thanks for the feedback!

**Comment by jzaruba** [comment]
Still getting the error after updating to 5.18.1

**Comment by jzaruba** [comment]
Oh nice, getting the error in EventLog now too! Thank you!
