### ISSUE TITLE
Works from the command line; fails in IntelliJ

### ISSUE THREAD

**Issue by fafhrd2** [jshiell/checkstyle-idea#402]
I'm getting an exception with the IntelliJ plugin that I don't get using it from the command line for the same directory of files.  Oddly, I've run it on every file individually inside IntelliJ without a problem; it's when I do a Current Module check.

The message is longer but this is all that I could capture.  Unfortunately, I cannot identify source code that will reproduce it outside of intellij, and our company considers source code to be confidential.  I understand that this may not be enough information for you to work with.

The scan failed due to an exception: An error occurred while scanning a file. Root cause: Absent Code attribute in method that is not native or abstract in class file org/json/JSONException java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file org/json/JSONException   at java.lang.ClassLoader.defineClass1(Native Method)   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)   at java.security.AccessController.doPrivileged(Native Method)   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)   at java.lang.Class.forName0(Native Method)   at java.lang.Class.forName(Class.java:348)   at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.safeLoad(ClassResolver.java:212)   at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.isLoadable(ClassResolver.java:190)   at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolveQualifiedName(ClassResolver.java:223)   at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolveMatchingExplicitImport(ClassResolver.java:130)   at com.puppycrawl.tools.checkstyle.checks.javadoc.ClassResolver.resolve(ClassResolver.java:78)   at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.resolveClass(AbstractTypeAwareCheck.java:241)   at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck.tryLoadClass(AbstractTypeAwareCheck.java:258)   at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractTypeAwareCheck$RegularClass.getClazz(AbstractTypeAwareCheck.java:470)   at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck$ExceptionInfo.getClazz(JavadocMethodCheck.java:1010)

**Comment by fafhrd2** [comment]
I thought that I could limit "Check module" to one package and its contents, but it seems to be actually checking the whole module.  This could simply be because it's too big.  I haven't found how to limit it to one package.
