### ISSUE TITLE
checkstyle threw a stacktrace unexpectedly while coding

### ISSUE THREAD

**Issue by cypressf** [jshiell/checkstyle-idea#413]
I wish I could give you more details to reproduce, but I'm not sure how. Let me know if there's any detail I can add that would be helpful, about my system, intellij version, etc.

```
CheckStyle threw an exception when scanning: GoogleSearchConsoleClientTest.java

org.infernus.idea.checkstyle.exception.CheckStylePluginException: Exception was thrown while processing /var/folders/6m/hstbhbz970d74xjngbq6d7p8tk379f/T/csi-f779df6b-e575-4ae9-958c-43888fef4fff/src/test/java/com/hubspot/googlesearchconsole/GoogleSearchConsoleClientTest.java
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:45)
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:70)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:44)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$33(CheckStyleInspection.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:86)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$32(CheckStyleInspection.java:58)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /var/folders/6m/hstbhbz970d74xjngbq6d7p8tk379f/T/csi-f779df6b-e575-4ae9-958c-43888fef4fff/src/test/java/com/hubspot/googlesearchconsole/GoogleSearchConsoleClientTest.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:318)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:274)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:68)
	... 10 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -115
	at java.lang.String.substring(String.java:1931)
	at com.puppycrawl.tools.checkstyle.api.FileContents.reportCppComment(FileContents.java:112)
	at com.puppycrawl.tools.checkstyle.api.FileContents.reportSingleLineComment(FileContents.java:96)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.mSINGLE_LINE_COMMENT(GeneratedJavaLexer.java:1116)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:331)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.postfixExpression(GeneratedJavaRecognizer.java:7571)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.unaryExpressionNotPlusMinus(GeneratedJavaRecognizer.java:7254)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.unaryExpression(GeneratedJavaRecognizer.java:7069)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.multiplicativeExpression(GeneratedJavaRecognizer.java:6934)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.additiveExpression(GeneratedJavaRecognizer.java:6885)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.shiftExpression(GeneratedJavaRecognizer.java:6828)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.relationalExpression(GeneratedJavaRecognizer.java:6745)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.equalityExpression(GeneratedJavaRecognizer.java:6696)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.andExpression(GeneratedJavaRecognizer.java:6667)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.exclusiveOrExpression(GeneratedJavaRecognizer.java:6638)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.inclusiveOrExpression(GeneratedJavaRecognizer.java:6609)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.logicalAndExpression(GeneratedJavaRecognizer.java:6580)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.logicalOrExpression(GeneratedJavaRecognizer.java:6551)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.conditionalExpression(GeneratedJavaRecognizer.java:2135)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.assignmentExpression(GeneratedJavaRecognizer.java:6303)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.expression(GeneratedJavaRecognizer.java:4764)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.expressionList(GeneratedJavaRecognizer.java:6063)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.argList(GeneratedJavaRecognizer.java:3435)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.postfixExpression(GeneratedJavaRecognizer.java:7539)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.unaryExpressionNotPlusMinus(GeneratedJavaRecognizer.java:7254)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.unaryExpression(GeneratedJavaRecognizer.java:7069)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.multiplicativeExpression(GeneratedJavaRecognizer.java:6934)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.additiveExpression(GeneratedJavaRecognizer.java:6885)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.shiftExpression(GeneratedJavaRecognizer.java:6828)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.relationalExpression(GeneratedJavaRecognizer.java:6745)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.equalityExpression(GeneratedJavaRecognizer.java:6696)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.andExpression(GeneratedJavaRecognizer.java:6667)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.exclusiveOrExpression(GeneratedJavaRecognizer.java:6638)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.inclusiveOrExpression(GeneratedJavaRecognizer.java:6609)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.logicalAndExpression(GeneratedJavaRecognizer.java:6580)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.logicalOrExpression(GeneratedJavaRecognizer.java:6551)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.conditionalExpression(GeneratedJavaRecognizer.java:2135)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.assignmentExpression(GeneratedJavaRecognizer.java:6303)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.expression(GeneratedJavaRecognizer.java:4764)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.initializer(GeneratedJavaRecognizer.java:4607)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.varInitializer(GeneratedJavaRecognizer.java:4521)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.variableDeclarator(GeneratedJavaRecognizer.java:4494)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.variableDefinitions(GeneratedJavaRecognizer.java:1555)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.declaration(GeneratedJavaRecognizer.java:1534)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5314)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4251)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:3917)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3319)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2541)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
	at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
	at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:441)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:177)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:338)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:308)
	... 12 more
```

**Comment by jshiell** [comment]
Thanks for the report!

Checkstyle isn't designed for scanning files on the fly - it's explicitly designed as a command-line tool for scanning well-formed Java source. As such, it makes no effort to deal with parse errors. And since we're scanning files on-the-fly we could (and will) hit malformed files - should IDEA invoke the check in the middle of editing. Most of the time these pop up as ANTLR exceptions, and there's handling code for hiding this from the user. However, every so often we get something else, such as the above.

I'll add this to the handling code, although it'll probably be next weekend at the earliest given my current schedule.

**Comment by jshiell** [comment]
Closed due to no further information. Please reopen if the problems wasn't resolved by the above.
