### ISSUE TITLE
Add support for static groups properties in ImportOrder

### ISSUE THREAD

**Issue by polarene** [jshiell/checkstyle-idea#473]
I'm using Checktyle-idea 5.35.5 and seems it doesn't support "static group" properties in the ImportOrder module (https://checkstyle.sourceforge.io/config_imports.html#ImportOrder).
I tried to import a rules file from an open source project I'm contributing and it fails when it reads these lines:
```
<module name="ImportOrder">
    ...
    <!-- static imports -->
    <property name="staticGroups" value="/^java\./,javax,org,com,lombok"/>
    <property name="separatedStaticGroups" value="true"/>
</module>
```
This is the stack trace:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Property 'staticGroups' in module ImportOrder does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:461)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'staticGroups' in module ImportOrder does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:164)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:172)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:456)
	... 7 more
```
The Maven Checkstyle plugin has no problems with these rules and the build is fine.

**Comment by jshiell** [comment]
What version of Checkstyle do you have selected?

**Comment by polarene** [comment]
Thanks! I had tried versions from 8.1 to a few later because I thought the second digit was a patch number... 🤦‍♂️ Now it works with **8.14**, the greater next available on the dropdown menu.
Sorry for the useless noise.
