### ISSUE TITLE
IllegalStateException: expecting RCURLY, found 'null'

### ISSUE THREAD

**Issue by petr-nehez** [jshiell/checkstyle-idea#475]
Unfortunately I cannot give you full decription of the issue and data for it, it has occurred only once in IntelliJ 2019.3.2.
It could happen due to some some unexpected state of file. I remember I was moving a method from one class to `JsonTools`.

Plugin version: `5.35.5`
CheckStyle version: `8.28`

This is the error from IntelliJ's EventLog:
```
The scan failed due to a parse error: IllegalStateException occurred while parsing file /home/petr/work/src/tipsport/tipsys2/commons/src/main/java/cz/tipsport/common/tools/JsonTools.java. 
Root cause: expecting RCURLY, found 'null' 
/home/petr/work/src/tipsport/tipsys2/commons/src/main/java/cz/tipsport/common/tools/JsonTools.java:119:1: expecting RCURLY, found 'null'   
at antlr.Parser.match(Parser.java:211)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2564)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)   
at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)   
at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)   
at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)   
at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)   
at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)   
at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)   
at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)   
at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)   
at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)   
at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)   
at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:43)   
at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$7(ScanFiles.java:197)   
at java.base/java.util.Optional.map(Optional.java:265)   
at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:197)   
at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:156)   
at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:78)   
at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:32)   
at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:274)   
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   
at java.base/java.lang.Thread.run(Thread.java:834) 
```

**Comment by jshiell** [comment]
Thanks for the report. This isn't unusual, I fear - Checkstyle isn't designed as a pluggable API, and is only designed to be run on syntactically correct code. The result is that we have to watch for a lot of edge cases where the code breaks in ways it shouldn't when run via the official command-line client. Every so often a new version of Checkstyle introduces a new case - this looks like one of them. 

I'll try and get this one covered later this week.

**Comment by jshiell** [comment]
Ah, sorry, when I read it at work earlier I thought that was coming from the inspection.

For the inspection we do suppress such things (mostly). But for the manually triggered scans we do log the error - as obviously if you've requested a scan then you'd expect some feedback. So I think the error being fed back is correct, as we've no way of determining a valid case (your source isn't currently parseable) vs an actual bug.

However, the message is over the top. I'll try improve it to skip the exception etc and make it more obvious it's legit.

**Comment by jshiell** [comment]
We no longer log the pointless exception to the event log - hopefully the message is clear enough, and we have debug logging if we ever do get a bug around this 🤞
