### ISSUE TITLE
Unable to import Checkstyle config

### ISSUE THREAD

**Issue by hashhar** [jshiell/checkstyle-idea#480]
Checkstyle version: 8.29
Checkstyle file: https://github.com/confluentinc/common/blob/master/build-tools/src/main/resources/checkstyle/checkstyle.xml

Logs:

```
2020-03-04 13:19:05,939 [1512161]   WARN - er.CheckStyleCodeStyleImporter - Failed to import style
org.infernus.idea.checkstyle.exception.CheckstyleServiceException: Error executing command 'OpLoadConfiguration': internal error - Failed to call com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration()
        at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:147)
        at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.loadConfiguration(CheckstyleActionsImpl.java:111)
        at org.infernus.idea.checkstyle.importer.CheckStyleCodeStyleImporter.loadConfiguration(CheckStyleCodeStyleImporter.java:85)
        at org.infernus.idea.checkstyle.importer.CheckStyleCodeStyleImporter.importScheme(CheckStyleCodeStyleImporter.java:54)
        at org.infernus.idea.checkstyle.importer.CheckStyleCodeStyleImporter.importScheme(CheckStyleCodeStyleImporter.java:22)
        at com.intellij.application.options.codeStyle.CodeStyleSchemesActions.importExternalCodeStyle(CodeStyleSchemesActions.java:130)
        at com.intellij.application.options.codeStyle.CodeStyleSchemesActions.chooseAndImport(CodeStyleSchemesActions.java:101)
        at com.intellij.application.options.codeStyle.CodeStyleSchemesActions.importScheme(CodeStyleSchemesActions.java:64)
        at com.intellij.application.options.schemes.AbstractSchemeActions$ImportAction.actionPerformed(AbstractSchemeActions.java:316)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:289)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:223)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:213)
        at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:207)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
        at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1434)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2418)
        at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:177)
        at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:129)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:159)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1430)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:151)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
        at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:292)
        at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:104)
        at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
        at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
        at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:133)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:123)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:119)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:252)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:254)
        at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:461)
        at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:415)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:361)
        at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:526)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:583)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:687)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:708)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:433)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1698)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1657)
        at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:86)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
        at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:86)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
        at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
        at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:294)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:263)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
        at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:116)
        at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
        at com.intellij.openapi.wm.impl.GlobalMenuLinux.lambda$_handleEvent$13(GlobalMenuLinux.java:696)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.infernus.idea.checkstyle.exception.CheckstyleServiceException: internal error - Failed to call com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration()
        at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.callLoadConfiguration(OpLoadConfiguration.java:161)
        at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.execute(OpLoadConfiguration.java:139)
        at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.execute(OpLoadConfiguration.java:44)
        at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
        ... 130 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.loadConfigurationForCheckstyle825AndAbove(OpLoadConfiguration.java:188)
        at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.callLoadConfiguration(OpLoadConfiguration.java:156)
        ... 133 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.puppycrawl.tools.checkstyle.api.SeverityLevel.
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at com.puppycrawl.tools.checkstyle.api.SeverityLevel.getInstance(SeverityLevel.java:66)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.endElement(ConfigurationLoader.java:563)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endNamespaceScope(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:196)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:311)
        at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:283)
        ... 139 more
```

**Comment by jshiell** [comment]
The exception suggests the `severity` is empty, and hence it can't find the matching enum. Did you set `checkstyle.customimportorder.severity` ?

**Comment by hashhar** [comment]
Thanks for catching that. I should've read the logs more carefully.

Will close this.

**Comment by jshiell** [comment]
My pleasure, glad to have helped 👍

**Comment by hashhar** [comment]
Also, I can see that you have both `IgnoringResolver` and `SimpleResolver`. So how can I pass the values for the properties to be resolved? Was unable to find any config. Does it take it from the pom file's section where checkstyle is configured?

**Comment by jshiell** [comment]
When you add the file (or click the edit button the config dialogue) you should be presented with a table of properties, at which point you can enter values for them.

We don't read the POM at all, as IDEA doesn't give us an extraction and I've no plans to integrate with Maven.
