### ISSUE TITLE
Plugin fails to load with "Failed to make relative" error. IntelliJ settings won't open

### ISSUE THREAD

**Issue by daniel-a-melo** [jshiell/checkstyle-idea#481]
The plugin fails to open with the error "java.lang.RuntimeException: Failed to make relative: $PRJ_DIR$\..\..\..\config\myconfig-checkstyle.xml"

(stacktrace trimmmed for brevity)

java.lang.RuntimeException: Failed to make relative: $PRJ_DIR$\..\..\..\config\myconfig-checkstyle.xml
	at org.infernus.idea.checkstyle.model.RelativeFileConfigurationLocation.makeProjectRelative(RelativeFileConfigurationLocation.java:57)
	at org.infernus.idea.checkstyle.model.RelativeFileConfigurationLocation.setLocation(RelativeFileConfigurationLocation.java:34)
	at org.infernus.idea.checkstyle.model.ConfigurationLocationFactory.create(ConfigurationLocationFactory.java:73)
	at org.infernus.idea.checkstyle.model.ConfigurationLocationFactory.create(ConfigurationLocationFactory.java:128)
	at org.infernus.idea.checkstyle.config.ProjectConfigurationState.deserialiseLocation(ProjectConfigurationState.java:242)
(...)
com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
(...)
Caused by: java.lang.NullPointerException
	at org.infernus.idea.checkstyle.util.FilePaths.relativePath(FilePaths.java:51)
	at org.infernus.idea.checkstyle.model.RelativeFileConfigurationLocation.makeProjectRelative(RelativeFileConfigurationLocation.java:50)
	... 126 more

IntelliJ's settings dialog won't be displayed with no errors displayed. The following stacktrace can be found at IntellJ's log:

(stacktrace trimmed for brevity)
	
2020-03-10 10:44:10,483 [1055450]  ERROR - openapi.options.ConfigurableEP - IntelliJ IDEA 2019.3.3  Build #IC-193.6494.35 
2020-03-10 10:44:10,483 [1055450]  ERROR - openapi.options.ConfigurableEP - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-10 10:44:10,483 [1055450]  ERROR - openapi.options.ConfigurableEP - OS: Windows 10 
2020-03-10 10:44:10,483 [1055450]  ERROR - openapi.options.ConfigurableEP - Plugin to blame: CheckStyle-IDEA version: 5.35.7 
2020-03-10 10:44:10,483 [1055450]  ERROR - openapi.options.ConfigurableEP - Last Action: ShowSettings 
2020-03-10 10:44:10,484 [1055451]  ERROR - e.actions.ShowSettingsUtilImpl - Argument for @NotNull parameter 'key' of com/intellij/CommonBundle.message must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/CommonBundle.message must not be null
	at com.intellij.CommonBundle.$$$reportNull$$$0(CommonBundle.java)
	at com.intellij.CommonBundle.message(CommonBundle.java)
	at com.intellij.openapi.options.ConfigurableEP.getDisplayName(ConfigurableEP.java:68)
	at com.intellij.openapi.options.ConfigurableEP.toString(ConfigurableEP.java:325)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:113)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:86)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:132)
(...)

**Version information:**

IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: CheckStyle-IDEA, InnerBuilder, MavenRunHelper, com.thvardhan.gradianto, com.tylerthrailkill.intellij.solarized, com.urswolfer.intellij.plugin.gerrit, org.antlr.intellij.plugin, org.asciidoctor.intellij.asciidoc, org.jetbrains.kotlin

**Checkstyle IDE configuration**:

(checkstyle-idea.xml)

`<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/../../../config/myconfig-checkstyle.xml:App Checks" />
        <entry key="checkstyle-version" value="6.19" />
        <entry key="copy-libs" value="true" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/../../../config/myconfig-checkstyle.xml:App Checks" />
        <entry key="property-2.checkstyle.AbbreviationAsWordInName.severity" value="" />
        <entry key="property-2.checkstyle.AvoidStarImport.severity" value="" />
        <entry key="property-2.checkstyle.ConstantName.applyToPackage" value="" />
        <entry key="property-2.checkstyle.ConstantName.applyToPrivate" value="" />
        <entry key="property-2.checkstyle.ConstantName.applyToProtected" value="" />
        <entry key="property-2.checkstyle.ConstantName.severity" value="" />
        <entry key="property-2.checkstyle.DesignForExtension.severity" value="" />
        <entry key="property-2.checkstyle.IllegalImport.illegalPkgs" value="" />
        <entry key="property-2.checkstyle.IllegalImport.severity" value="" />
        <entry key="property-2.checkstyle.JavadocParagraph.severity" value="" />
        <entry key="property-2.checkstyle.MissingSwitchDefault.severity" value="" />
        <entry key="property-2.checkstyle.NewlineAtEndOfFile.lineSeparator" value="" />
        <entry key="property-2.checkstyle.NewlineAtEndOfFile.severity" value="" />
        <entry key="property-2.checkstyle.NoTrailingWhitespace.severity" value="" />
        <entry key="property-2.checkstyle.NonUnixLineSeparator.severity" value="" />
        <entry key="property-2.checkstyle.ParameterAssignment.severity" value="" />
        <entry key="property-2.checkstyle.ParameterNumber.max" value="" />
        <entry key="property-2.checkstyle.ParameterNumber.severity" value="" />
        <entry key="property-2.checkstyle.VariableDeclarationUsageDistance.severity" value="" />
        <entry key="property-2.checkstyle.VariableDeclarationUsageDistance.validateBetweenScopes" value="" />
        <entry key="property-2.checkstyle.suppressions.file" value="checkstyle-suppressions.xml" />
        <entry key="scan-before-checkin" value="false" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>`

**Comment by jshiell** [comment]
Thanks for the report. This is doubly bad, since we're leaking the error as well, which is breaking the pref dialogue. I'll try have a look this weekend.

The oddity here is that we stopped writing out `PRJ_DIR` in mid-2018, as IDEA has its own variable for use here (`PROJECT_DIR`). The configuration should have been converted to use the new form the next time the configuration was saved. So I'm not quite sure why `PRJ_DIR` is still present. In any case, we dropped support for this last month, as I figured 18 months should have been heaps of time for migration, and it made the code quite a bit simpler. I may have been wrong.

The quick fix, to get you working again, should be to manually change $PRJ_DIR$ to $PROJECT_DIR$.

**Comment by daniel-a-melo** [comment]
Thanks for the response. 

I confirm that manually changing to `$PROJECT_DIR$` fixes the issue

**Comment by jshiell** [comment]
Great news - I'll still try get it fixed this weekend, in any case 👍

**Comment by jshiell** [comment]
And I've just cut a release with it, so hopefully this will blight no more people.
