### ISSUE TITLE
Cannot import checkstyle.xml from spring-boot-admin

### ISSUE THREAD

**Issue by andreashouben** [jshiell/checkstyle-idea#510]
Hi, I recently started as co-maintainer for spring-boot-admin. The project uses checkstyle (Version 8.37).

We had no  luck importing the checkstyle.xml into the checkstyle plugin. Tried it on Windows, LInux and Mac OS.

The checkstyle.xml can be found [here](https://github.com/codecentric/spring-boot-admin/blob/master/src/checkstyle/checkstyle.xml)
The required header file is in the same folder. We link it by supplying the absolute path.

The error that appears is the same on all systems:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module com.puppycrawl.tools.checkstyle.TreeWalker - cannot initialize module io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor - Fehler beim Instanziieren der Klasse 'io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor'. Es war auch nicht möglich, sie als null zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: https://checkstyle.org/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor - Fehler beim Instanziieren der Klasse 'io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor'. Es war auch nicht möglich, sie als null zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: https://checkstyle.org/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:125)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
	... 7 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Fehler beim Instanziieren der Klasse 'io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor'. Es war auch nicht möglich, sie als null zu instanziieren. Bitte prüfen Sie, dass der Klassenname als kanonischer Name angegeben wurde oder lesen Sie, wie Sie abgekürzte Namen konfigurieren: https://checkstyle.org/config.html#Packages. Bitte prüfen Sie auch, dass der angegebene ClassLoader des Checkers richtig konfiguriert ist.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:215)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:116)
	... 9 more
```

I could not find a solution for that problem so I'm asking here for help :)

**Comment by jshiell** [comment]
Have you added the JAR file containing the custom check `io.spring.javaformat.checkstyle.check.SpringHideUtilityClassConstructor` into the third-party classpath section in the config panel?

**Comment by andreashouben** [comment]
I included the file that contains that class and that actually did the trick:
![image](https://user-images.githubusercontent.com/3708288/102612046-57ab1e80-4130-11eb-8597-a76298853467.png)
Thank you so much for your (extremely quick) help. 👍
