### ISSUE TITLE
Do not request resource from classloader using path with leading slash

### ISSUE THREAD

**Issue by jshiell** [jshiell/checkstyle-idea#534]
Idea: 2021.2, plugin last version download and install  from your web yesterday.

Reported by Robert ORÁLEK.

``` 
com.intellij.diagnostic.PluginException: .//../checkstyle-filter.xml [Plugin: CheckStyle-IDEA]
                at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:504)
                at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:471)
                at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
                at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1396)
                at org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader.getResource(ChildFirstURLClassLoader.java:60)
                at org.infernus.idea.checkstyle.model.ConfigurationLocation.existsOnClasspath(ConfigurationLocation.java:257)
                at org.infernus.idea.checkstyle.model.ConfigurationLocation.findFile(ConfigurationLocation.java:248)
                at org.infernus.idea.checkstyle.model.ConfigurationLocation.resolveAssociatedFile(ConfigurationLocation.java:230)
                at org.infernus.idea.checkstyle.model.FileConfigurationLocation.resolveAssociatedFile(FileConfigurationLocation.java:97)
                at org.infernus.idea.checkstyle.service.RulesContainer$ConfigurationLocationRulesContainer.resolveAssociatedFile(RulesContainer.java:68)
                at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.resolveAndUpdateFile(OpLoadConfiguration.java:225)
                at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.checkFilenameForProperty(OpLoadConfiguration.java:213)
                at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.resolveFilePaths(OpLoadConfiguration.java:197)
                at org.infernus.idea.checkstyle.service.cmd.OpLoadConfiguration.execute(OpLoadConfiguration.java:141)
                at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.loadConfig(OpCreateChecker.java:98)
                at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:54)
                at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
                at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
                at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
                at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
                at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
```

**Comment by jshiell** [comment]
Fixed in 15fda11c86920a4e1270a2d0de9370de686ee975
