### ISSUE TITLE
Not working with spring-javaformat

### ISSUE THREAD

**Issue by ttddyy** [jshiell/checkstyle-idea#550]
I was trying to apply checkstyle rules with [spring-javaformat](https://github.com/spring-io/spring-javaformat).

IntelliJ IDEA: 2021.3.2 (Ultimate Edition)
Checkstyle Plugin: 5.61.0
Spring Javaformat: 0.0.31

Based on [here](https://github.com/spring-io/spring-javaformat#checkstyle-1
), I have created this `checkstyle.xml`:

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
   		"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
   		"https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="com.puppycrawl.tools.checkstyle.Checker">
	<module name="io.spring.javaformat.checkstyle.SpringChecks" />
</module>
```

When I tried to add this checkstyle file, received the following exceptions:

```java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module io.spring.javaformat.checkstyle.SpringChecks - Unable to instantiate 'io.spring.javaformat.checkstyle.SpringChecks' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'io.spring.javaformat.checkstyle.SpringChecks' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:215)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:463)
	... 7 more
```

After reading #510, I added `spring-javaformat-checkstyle-0.0.31.jar` as "Third-Party Checks".

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/459116/153728073-9750fead-fcfe-4313-b0f1-78c24e168a32.png">

It passed the above, but still failed with:

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'io.spring.javaformat.checkstyle.check.SpringLeadingWhitespaceCheck' class, it is also not possible to instantiate it as null. 
```

I see `SpringLeadingWhitespaceCheck` exists in the `spring-javaformat-checkstyle-0.0.31.jar`.
```
> jar tvf spring-javaformat-checkstyle-0.0.31.jar | grep SpringLeadingWhitespaceCheck
 4149 Wed Feb 02 23:03:28 PST 2022 io/spring/javaformat/checkstyle/check/SpringLeadingWhitespaceCheck.class
```

Here is the complete error:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module io.spring.javaformat.checkstyle.check.SpringLeadingWhitespaceCheck - Unable to instantiate 'io.spring.javaformat.checkstyle.check.SpringLeadingWhitespaceCheck' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:128)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at io.spring.javaformat.checkstyle.SpringConfigurationLoader.initialize(SpringConfigurationLoader.java:92)
	at io.spring.javaformat.checkstyle.SpringConfigurationLoader.createModule(SpringConfigurationLoader.java:81)
	at io.spring.javaformat.checkstyle.SpringConfigurationLoader.load(SpringConfigurationLoader.java:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.spring.javaformat.checkstyle.SpringConfigurationLoader.load(SpringConfigurationLoader.java:55)
	at io.spring.javaformat.checkstyle.SpringChecks.finishLocalSetup(SpringChecks.java:103)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'io.spring.javaformat.checkstyle.check.SpringLeadingWhitespaceCheck' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:215)
	at io.spring.javaformat.checkstyle.FilteredModuleFactory.createModule(FilteredModuleFactory.java:50)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:119)
	... 23 more

```

**Comment by tsjensen** [comment]
You may have to press Apply in between, i.e. after adding the 3rd party jar.

**Comment by ttddyy** [comment]
@tsjensen Yes, I've done that. So, it's already listed when I open the preference window, but the error still shows up.

**Comment by tsjensen** [comment]
Ok, just an idea, I'll be quiet then. 😊

**Comment by jshiell** [comment]
Sorry for the delay, I spent the weekend trapped stripping wallpaper  😢 

The problem is that your Spring module is spread over two JAR files - [MVNRepository](https://mvnrepository.com/artifact/io.spring.javaformat/spring-javaformat-checkstyle/0.0.31) shows the dependency on [spring-javaformat-config](https://mvnrepository.com/artifact/io.spring.javaformat/spring-javaformat-config).

After adding both JARs it works for me. 

<img width="602" alt="Screenshot 2022-02-14 at 19 21 43" src="https://user-images.githubusercontent.com/1030482/153931794-08a0daf5-b39f-4931-8ea3-4461736a6c81.png">

Likewise, you need to do the same when running it via the CLI:

```bash
java -cp test-configs/spring-javaformat-checkstyle-0.0.31.jar:test-configs/spring-javaformat-config-0.0.31.jar:$HOME/Downloads/checkstyle-9.3-all.jar com.puppycrawl.tools.checkstyle.Main -c test-configs/issue-550.xml src
```

**Comment by ttddyy** [comment]
Oh, ic. Thanks now it works!!
