### ISSUE TITLE
The source file could not be parsed by Checkstyle. - java 16 records

### ISSUE THREAD

**Issue by pearceeverydaylabs** [jshiell/checkstyle-idea#575]
1. Fresh plugin install
2. Set `Checkstyle Version` to 8.29 in Preferences > Tools > Checkstyle
    *  I'm using the latest maven checkstyle plugin version: 3.1.2, [which uses checkstyle 8.29](https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html)
4. select `Google Checks`
5. click `Check Project`

A scan begins, but ends less than a second later with the parse error.

After enabling debug logging, the error is because I'm using java 16 with record classes. 

Seems like something in the toolchain is old and doesn't know about my sweet new java 16 goodies, but not sure how to pinpoint what that is 🤔 
```
2022-06-05 13:36:56,874 [ 699765]   FINE - #o.i.i.c.c.ScanFiles - Parse exception caught during scan
org.infernus.idea.checkstyle.exception.CheckStylePluginParseException: IllegalStateException occurred while parsing file /redacted/path/to/MyRedactedClass.java.
	at org.infernus.idea.checkstyle.service.ExceptionWrapper.wrap(ExceptionWrapper.java:48)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:132)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:59)
	at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$10(ScanFiles.java:210)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$12(ScanFiles.java:210)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:213)
	at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:169)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:83)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:36)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /redacted/path/to/MyRedactedClass.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:73)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:50)
	at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:21)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	... 25 more
Caused by: java.lang.IllegalStateException: /redacted/path/to/MyRedactedClass.java:7:8: unexpected token: record
	at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:93)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:411)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
	... 34 more
Caused by: /redacted/path/to/MyRedactedClass.java:7:8: unexpected token: record
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:584)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
	... 36 more
```

**Comment by jshiell** [comment]
Thanks @tsjensen - indeed, the parser didn't handle records at all until [8.35](https://checkstyle.sourceforge.io/releasenotes.html), with most support seeming to land in 8.36. Selecting a more recent version of Checkstyle should fix your issue 🤞
