### ISSUE TITLE
The scan failed due to an exception: An error occurred while scanning a file.

### ISSUE THREAD

**Issue by TheDeadOne** [jshiell/checkstyle-idea#606]
CheckStyle-IDEA 5.76.0
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```
The scan failed due to an exception: An error occurred while scanning a file. 
Root cause: loader constraint violation: when resolving method 'void com.intellij.openapi.application.ReadAction.run(com.intellij.util.ThrowableRunnable)'
the class loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @67dfde8c of the current class,
org/infernus/idea/checkstyle/service/CheckStyleAuditListener, and the class loader com.intellij.util.lang.PathClassLoader
@528931cf for the method's defining class, com/intellij/openapi/application/ReadAction, have different Class objects
for the type com/intellij/util/ThrowableRunnable used in the signature (org.infernus.idea.checkstyle.service.CheckStyleAuditListener
is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @67dfde8c, parent loader
com.intellij.ide.plugins.cl.PluginClassLoader @6b2c937d; com.intellij.openapi.application.ReadAction is in unnamed module
of loader com.intellij.util.lang.PathClassLoader @528931cf, parent loader 'platform') java.lang.LinkageError: loader constraint
violation: when resolving method 'void com.intellij.openapi.application.ReadAction.run(com.intellij.util.ThrowableRunnable)'
the class loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @67dfde8c of the current class,
org/infernus/idea/checkstyle/service/CheckStyleAuditListener, and the class loader com.intellij.util.lang.PathClassLoader
@528931cf for the method's defining class, com/intellij/openapi/application/ReadAction, have different Class objects for
the type com/intellij/util/ThrowableRunnable used in the signature (org.infernus.idea.checkstyle.service.CheckStyleAuditListener
is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @67dfde8c, parent loader
com.intellij.ide.plugins.cl.PluginClassLoader @6b2c937d; com.intellij.openapi.application.ReadAction is in unnamed module
of loader com.intellij.util.lang.PathClassLoader @528931cf, parent loader 'platform')
   at org.infernus.idea.checkstyle.service.CheckStyleAuditListener.auditFinished(CheckStyleAuditListener.java:61)
   at com.puppycrawl.tools.checkstyle.Checker.fireAuditFinished(Checker.java:271)
   at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:231)
   at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:73)
   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:50)
   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:21)
   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)
   at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:59)
   at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$10(ScanFiles.java:207)
   at java.base/java.util.Optional.map(Optional.java:265)
   at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$12(ScanFiles.java:207)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
   at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:210)
   at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:166)
   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:82)
   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:35)
   at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:294)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
   at java.base/java.security.AccessController.doPrivileged(Native Method)
   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by marcinkunert** [comment]
Same(?) is happening for me.

CheckStyle-IDEA 5.76.0
IntelliJ IDEA 2021.3.3 (Ultimate Edition) Build #IU-213.7172.25, built on March 15, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```
The scan failed due to an exception: An error occurred while scanning a file. Root cause: loader constraint violation: when resolving method 'void com.intellij.openapi.application.ReadAction.run(com.intellij.util.ThrowableRunnable)' the class loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @239de4bc of the current class, org/infernus/idea/checkstyle/service/CheckStyleAuditListener, and the class loader com.intellij.util.lang.PathClassLoader @3a03464 for the method's defining class, com/intellij/openapi/application/ReadAction, have different Class objects for the type com/intellij/util/ThrowableRunnable used in the signature (org.infernus.idea.checkstyle.service.CheckStyleAuditListener is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @239de4bc, parent loader com.intellij.ide.plugins.cl.PluginClassLoader @369819d3; com.intellij.openapi.application.ReadAction is in unnamed module of loader com.intellij.util.lang.PathClassLoader @3a03464, parent loader 'platform') java.lang.LinkageError: loader constraint violation: when resolving method 'void com.intellij.openapi.application.ReadAction.run(com.intellij.util.ThrowableRunnable)' the class loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @239de4bc of the current class, org/infernus/idea/checkstyle/service/CheckStyleAuditListener, and the class loader com.intellij.util.lang.PathClassLoader @3a03464 for the method's defining class, com/intellij/openapi/application/ReadAction, have different Class objects for the type com/intellij/util/ThrowableRunnable used in the signature (org.infernus.idea.checkstyle.service.CheckStyleAuditListener is in unnamed module of loader org.infernus.idea.checkstyle.util.ChildFirstURLClassLoader @239de4bc, parent loader com.intellij.ide.plugins.cl.PluginClassLoader @369819d3; com.intellij.openapi.application.ReadAction is in unnamed module of loader com.intellij.util.lang.PathClassLoader @3a03464, parent loader 'platform')   at org.infernus.idea.checkstyle.service.CheckStyleAuditListener.auditFinished(CheckStyleAuditListener.java:61)   at com.puppycrawl.tools.checkstyle.Checker.fireAuditFinished(Checker.java:265)   at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:234)   at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:73)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:50)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:21)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)   at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:59)   at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$10(ScanFiles.java:207)   at java.base/java.util.Optional.map(Optional.java:265)   at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$12(ScanFiles.java:207)   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)   at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:210)   at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:166)   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:82)   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:35)   at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:294)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at java.base/java.security.AccessController.doPrivileged(Native Method)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by marcinkunert** [comment]
Updated to IntelliJ IDEA 2022.3.2 (Ultimate Edition) and it works fine again! :)

**Comment by TheDeadOne** [comment]
> Updated to IntelliJ IDEA 2022.3.2 (Ultimate Edition) and it works fine again! :)

Unfortunately, this solution is not available for russians :(

**Comment by TheDeadOne** [comment]
The latest version that works with IntelliJ IDEA 2021.3.3 is 5.74.0.

**Comment by jshiell** [comment]
Given the error, I'm going to guess it's related to the fix for #595. It's odd, however, given the project was build against 2021.3.3.

I'm afraid it's not going to get fixed though - given 2023.1 is about to be released, and I need to update the build version anyway to ensure compatibility with that, I'm afraid I'll be increasing the minimum version to 2022.1. You'll need to continue to use 5.74.0 with 2021.3.3. Sorry.

**Comment by artseroff** [comment]
TheDeadOne, I have the same IDE version, just install the plugin with 5.73.0 version and everything works great!

**Comment by XUPTLiYipeng** [comment]
Solution：install the Checkstyle 5.73.0 here [https://plugins.jetbrains.com/plugin/1065-checkstyle-idea/versions/stable](https://github.com/jshiell/checkstyle-idea/issues/url)
My IDEA version is 2021.3.3 Utimate and I meet the same problem
