### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by simonstratmann** [jshiell/checkstyle-idea#634]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.infernus.idea.checkstyle.actions.Close' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: CheckStyle-IDEA]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

I'm a plugin developer myself, the fix is pretty easy. Add

```
    @Override
    public @NotNull ActionUpdateThread getActionUpdateThread() {
        return ActionUpdateThread.BGT;
    }
```

to all action classes.

**Comment by jshiell** [comment]
Thanks muchly - the only thing better than a clear bug report is one where you're told the fix as well 😁 Fixed in 5.88.1!
